from ibapi.common import BarData as BarData, HistogramData as HistogramData, HistoricalTick as HistoricalTick, HistoricalTickBidAsk as HistoricalTickBidAsk, HistoricalTickLast as HistoricalTickLast, TickAttribBidAsk as TickAttribBidAsk, TickAttribLast as TickAttribLast
from ibapi.contract import ComboLeg as ComboLeg, Contract as Contract, ContractDetails as ContractDetails, DeltaNeutralContract as DeltaNeutralContract, FundAssetType as FundAssetType, FundDistributionPolicyIndicator as FundDistributionPolicyIndicator
from ibapi.execution import Execution as Execution, OptionExerciseType as OptionExerciseType
from ibapi.ineligibility_reason import IneligibilityReason as IneligibilityReason
from ibapi.order import Order as Order, OrderComboLeg as OrderComboLeg
from ibapi.order_condition import ContractCondition as ContractCondition, ExecutionCondition as ExecutionCondition, MarginCondition as MarginCondition, OperatorCondition as OperatorCondition, OrderCondition as OrderCondition, PercentChangeCondition as PercentChangeCondition, PriceCondition as PriceCondition, TimeCondition as TimeCondition, VolumeCondition as VolumeCondition
from ibapi.order_state import OrderAllocation as OrderAllocation, OrderState as OrderState
from ibapi.protobuf.ContractDetails_pb2 import ContractDetails as ContractDetailsProto
from ibapi.protobuf.Contract_pb2 import Contract as ContractProto
from ibapi.protobuf.Execution_pb2 import Execution as ExecutionProto
from ibapi.protobuf.HistogramDataEntry_pb2 import HistogramDataEntry as HistogramDataEntryProto
from ibapi.protobuf.HistoricalDataBar_pb2 import HistoricalDataBar as HistoricalDataBarProto
from ibapi.protobuf.HistoricalTickBidAsk_pb2 import HistoricalTickBidAsk as HistoricalTickBidAskProto
from ibapi.protobuf.HistoricalTickLast_pb2 import HistoricalTickLast as HistoricalTickLastProto
from ibapi.protobuf.HistoricalTick_pb2 import HistoricalTick as HistoricalTickProto
from ibapi.protobuf.OrderCondition_pb2 import OrderCondition as OrderConditionProto
from ibapi.protobuf.OrderState_pb2 import OrderState as OrderStateProto
from ibapi.protobuf.Order_pb2 import Order as OrderProto
from ibapi.softdollartier import SoftDollarTier as SoftDollarTier
from ibapi.tag_value import TagValue as TagValue
from ibapi.utils import decimalMaxString as decimalMaxString, floatMaxString as floatMaxString, getEnumTypeFromString as getEnumTypeFromString, isValidIntValue as isValidIntValue

@staticmethod
def decodeContract(contractProto: ContractProto) -> Contract: ...
@staticmethod
def decodeComboLegs(contractProto: ContractProto) -> list[ComboLeg]: ...
@staticmethod
def decodeOrderComboLegs(contractProto: ContractProto) -> list[OrderComboLeg]: ...
@staticmethod
def decodeDeltaNeutralContract(contractProto: ContractProto) -> DeltaNeutralContract: ...
@staticmethod
def decodeExecution(executionProto: ExecutionProto) -> Execution: ...
@staticmethod
def decodeOrder(orderId: int, contractProto: ContractProto, orderProto: OrderProto) -> Order: ...
def decodeConditions(orderProto: OrderProto) -> list[OrderCondition]: ...
@staticmethod
def setConditionFields(orderConditionProto: OrderConditionProto, orderCondition: OrderCondition): ...
@staticmethod
def setOperatorConditionFields(orderConditionProto: OrderConditionProto, operatorCondition: OperatorCondition): ...
@staticmethod
def setContractConditionFields(orderConditionProto: OrderConditionProto, contractCondition: ContractCondition): ...
@staticmethod
def createPriceCondition(orderConditionProto: OrderConditionProto) -> PriceCondition: ...
@staticmethod
def createTimeCondition(orderConditionProto: OrderConditionProto) -> TimeCondition: ...
@staticmethod
def createMarginCondition(orderConditionProto: OrderConditionProto) -> MarginCondition: ...
@staticmethod
def createExecutionCondition(orderConditionProto: OrderConditionProto) -> ExecutionCondition: ...
@staticmethod
def createVolumeCondition(orderConditionProto: OrderConditionProto) -> VolumeCondition: ...
@staticmethod
def createPercentChangeCondition(orderConditionProto: OrderConditionProto) -> PercentChangeCondition: ...
@staticmethod
def decodeSoftDollarTier(orderProto: OrderProto) -> SoftDollarTier: ...
@staticmethod
def decodeTagValueList(protoMap: dict[str, str]) -> list[TagValue]: ...
@staticmethod
def decodeOrderState(orderStateProto: OrderStateProto) -> OrderState: ...
@staticmethod
def decodeOrderAllocations(orderStateProto: OrderStateProto) -> list[OrderAllocation]: ...
@staticmethod
def decodeContractDetails(contractProto: ContractProto, contractDetailsProto: ContractDetailsProto, isBond: bool) -> ContractDetails: ...
@staticmethod
def decodeIneligibilityReasonList(contractDetailsProto: ContractDetailsProto) -> list[IneligibilityReason]: ...
@staticmethod
def setLastTradeDate(lastTradeDateOrContractMonth: str, contract: ContractDetails, isBond: bool): ...
@staticmethod
def decodeHistoricalTick(historicalTickProto: HistoricalTickProto) -> HistoricalTick: ...
@staticmethod
def decodeHistoricalTickBidAsk(historicalTickBidAskProto: HistoricalTickBidAskProto) -> HistoricalTickBidAsk: ...
@staticmethod
def decodeHistoricalTickLast(historicalTickLastProto: HistoricalTickLastProto) -> HistoricalTickLast: ...
@staticmethod
def decodeHistogramDataEntry(histogramDataEntryProto: HistogramDataEntryProto) -> HistogramData: ...
@staticmethod
def decodeHistoricalDataBar(historicalDataBarProto: HistoricalDataBarProto) -> BarData: ...
