from ibapi.contract import Contract as Contract
from ibapi.execution import Execution as Execution, OptionExerciseType as OptionExerciseType
from ibapi.utils import floatMaxString as floatMaxString, getEnumTypeFromString as getEnumTypeFromString

def decodeContract(contractProto): ...
def decodeExecution(executionProto): ...
