from _typeshed import Incomplete
from ibapi import comm as comm
from ibapi.common import UNSET_DOUBLE as UNSET_DOUBLE
from ibapi.enum_implem import Enum as Enum
from ibapi.object_implem import Object as Object
from ibapi.utils import decode as decode

class OrderCondition(Object):
    Price: int
    Time: int
    Margin: int
    Execution: int
    Volume: int
    PercentChange: int
    condType: Incomplete
    isConjunctionConnection: bool
    def __init__(self, condType) -> None: ...
    def type(self): ...
    def And(self): ...
    def Or(self): ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...

class ExecutionCondition(OrderCondition):
    secType: Incomplete
    exchange: Incomplete
    symbol: Incomplete
    def __init__(self, secType=None, exch=None, symbol=None) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...

class OperatorCondition(OrderCondition):
    isMore: Incomplete
    def __init__(self, condType=None, isMore=None) -> None: ...
    def valueToString(self) -> str: ...
    def setValueFromString(self, text: str) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...

class MarginCondition(OperatorCondition):
    percent: Incomplete
    def __init__(self, isMore=None, percent=None) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...
    def valueToString(self) -> str: ...
    def setValueFromString(self, text: str) -> None: ...

class ContractCondition(OperatorCondition):
    conId: Incomplete
    exchange: Incomplete
    def __init__(self, condType=None, conId=None, exch=None, isMore=None) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...

class TimeCondition(OperatorCondition):
    time: Incomplete
    def __init__(self, isMore=None, time=None) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...
    def valueToString(self) -> str: ...
    def setValueFromString(self, text: str) -> None: ...

class PriceCondition(ContractCondition):
    TriggerMethodEnum: Incomplete
    price: Incomplete
    triggerMethod: Incomplete
    def __init__(self, triggerMethod=None, conId=None, exch=None, isMore=None, price=None) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...
    def valueToString(self) -> str: ...
    def setValueFromString(self, text: str) -> None: ...

class PercentChangeCondition(ContractCondition):
    changePercent: Incomplete
    def __init__(self, conId=None, exch=None, isMore=None, changePercent=...) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...
    def valueToString(self) -> str: ...
    def setValueFromString(self, text: str) -> None: ...

class VolumeCondition(ContractCondition):
    volume: Incomplete
    def __init__(self, conId=None, exch=None, isMore=None, volume=None) -> None: ...
    def decode(self, fields) -> None: ...
    def make_fields(self): ...
    def valueToString(self) -> str: ...
    def setValueFromString(self, text: str) -> None: ...

def Create(condType): ...
