
# -----------------------------------------------------------------------------------------------
[project]
name = "types-ibapi"
dynamic = ["version"]
description = "This is the Python package types-ibapi."

readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    { name = "Tony Lee", email = "iamtonylee@gmail.com" },
]

# Check https://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Typing :: Stubs Only",
]

dependencies = [
]


# -----------------------------------------------------------------------------------------------
[project.optional-dependencies]
dev = [
    "pytest",
]


# -----------------------------------------------------------------------------------------------
[project.urls]
Homepage = "https://github.com/hktonylee/ibapi_stubs"
Repository = "https://github.com/hktonylee/ibapi_stubs"


# -----------------------------------------------------------------------------------------------
[project.scripts]
ibapi_stubs = "ibapi_stubs.cli:main"


# -----------------------------------------------------------------------------------------------
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

# -----------------------------------------------------------------------------------------------
[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
# Typical: tags like v1.2.3 or 1.2.3 are accepted; tune if needed.
version_scheme = "guess-next-dev"

[tool.hatch.build.targets.wheel]
# No Python packages; we're shipping stub files as wheel data
packages = []
include = [
  "src/ibapi-stubs/**",
]

[tool.hatch.build.targets.sdist]
include = [
  "src/ibapi-stubs/**",
  "pyproject.toml",
  "README.md",
  "LICENSE",
]


# -----------------------------------------------------------------------------------------------
# [tool.setuptools]
# package-dir = {"" = "src" }
# 
# [tool.setuptools.packages.find]
# where = ["./src/"]
# include = []
# 
# [tool.setuptools.package-data]
# "ibapi-stubs" = ["py.typed", "**/*.pyi"]
# 
# [tool.setuptools_scm]


# -----------------------------------------------------------------------------------------------
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]


# -----------------------------------------------------------------------------------------------
[tool.isort]
profile = "black"


