
# -----------------------------------------------------------------------------------------------
[project]
name = "ibapi_stubs"
dynamic = ["version"]
description = "This is the Python package ibapi_stubs."

readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Tony Lee", email = "iamtonylee@gmail.com" },
]

# Check https://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Typing :: Stubs Only",
]

dependencies = [
]


# -----------------------------------------------------------------------------------------------
[project.optional-dependencies]
dev = [
    "pytest",
]


# -----------------------------------------------------------------------------------------------
[project.urls]
Homepage = "https://github.com/hktonylee/ibapi_stubs"
Repository = "https://github.com/hktonylee/ibapi_stubs"


# -----------------------------------------------------------------------------------------------
[project.scripts]
ibapi_stubs = "ibapi_stubs.cli:main"


# -----------------------------------------------------------------------------------------------
[build-system]
requires = ["setuptools >= 64", "setuptools_scm >= 8"]
build-backend = "setuptools.build_meta"


# -----------------------------------------------------------------------------------------------
[tool.setuptools.packages.find]
where = ["./src/"]
include = ["ibapi_stubs"]


# -----------------------------------------------------------------------------------------------
[tool.setuptools.package-data]
ibapi_stubs = ["py.typed"]


# -----------------------------------------------------------------------------------------------
[tool.setuptools_scm]


# -----------------------------------------------------------------------------------------------
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]


# -----------------------------------------------------------------------------------------------
[tool.isort]
profile = "black"


