from _typeshed import Incomplete

logger: Incomplete

class Connection:
    host: Incomplete
    port: Incomplete
    socket: Incomplete
    wrapper: Incomplete
    lock: Incomplete
    def __init__(self, host, port) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self): ...
    def sendMsg(self, msg): ...
    def recvMsg(self): ...
