from _typeshed import Incomplete
from ibapi.const import NO_VALID_ID as NO_VALID_ID
from ibapi.errors import CONNECT_FAIL as CONNECT_FAIL, FAIL_CREATE_SOCK as FAIL_CREATE_SOCK
from ibapi.utils import currentTimeMillis as currentTimeMillis

logger: Incomplete

class Connection:
    host: Incomplete
    port: Incomplete
    socket: Incomplete
    wrapper: Incomplete
    lock: Incomplete
    def __init__(self, host, port) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self): ...
    def sendMsg(self, msg): ...
    def recvMsg(self): ...
