from _typeshed import Incomplete
from ibapi import order_condition as order_condition
from ibapi.const import UNSET_DOUBLE as UNSET_DOUBLE
from ibapi.contract import ComboLeg as ComboLeg
from ibapi.object_implem import Object as Object
from ibapi.order import OrderComboLeg as OrderComboLeg
from ibapi.server_versions import MIN_CLIENT_VER as MIN_CLIENT_VER, MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE as MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE, MIN_SERVER_VER_BOND_ACCRUED_INTEREST as MIN_SERVER_VER_BOND_ACCRUED_INTEREST, MIN_SERVER_VER_CASH_QTY as MIN_SERVER_VER_CASH_QTY, MIN_SERVER_VER_CUSTOMER_ACCOUNT as MIN_SERVER_VER_CUSTOMER_ACCOUNT, MIN_SERVER_VER_DURATION as MIN_SERVER_VER_DURATION, MIN_SERVER_VER_D_PEG_ORDERS as MIN_SERVER_VER_D_PEG_ORDERS, MIN_SERVER_VER_FA_PROFILE_DESUPPORT as MIN_SERVER_VER_FA_PROFILE_DESUPPORT, MIN_SERVER_VER_MODELS_SUPPORT as MIN_SERVER_VER_MODELS_SUPPORT, MIN_SERVER_VER_ORDER_CONTAINER as MIN_SERVER_VER_ORDER_CONTAINER, MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS as MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS, MIN_SERVER_VER_PEGGED_TO_BENCHMARK as MIN_SERVER_VER_PEGGED_TO_BENCHMARK, MIN_SERVER_VER_POST_TO_ATS as MIN_SERVER_VER_POST_TO_ATS, MIN_SERVER_VER_PRICE_MGMT_ALGO as MIN_SERVER_VER_PRICE_MGMT_ALGO, MIN_SERVER_VER_PROFESSIONAL_CUSTOMER as MIN_SERVER_VER_PROFESSIONAL_CUSTOMER, MIN_SERVER_VER_SOFT_DOLLAR_TIER as MIN_SERVER_VER_SOFT_DOLLAR_TIER, MIN_SERVER_VER_SSHORTX_OLD as MIN_SERVER_VER_SSHORTX_OLD, MIN_SERVER_VER_WHAT_IF_EXT_FIELDS as MIN_SERVER_VER_WHAT_IF_EXT_FIELDS
from ibapi.softdollartier import SoftDollarTier as SoftDollarTier
from ibapi.tag_value import TagValue as TagValue
from ibapi.utils import SHOW_UNSET as SHOW_UNSET, decode as decode, isPegBenchOrder as isPegBenchOrder
from ibapi.wrapper import DeltaNeutralContract as DeltaNeutralContract

logger: Incomplete

class OrderDecoder(Object):
    contract: Incomplete
    order: Incomplete
    orderState: Incomplete
    version: Incomplete
    serverVersion: Incomplete
    def __init__(self, contract, order, orderState, version, serverVersion) -> None: ...
    def decodeOrderId(self, fields) -> None: ...
    def decodeContractFields(self, fields) -> None: ...
    def decodeAction(self, fields) -> None: ...
    def decodeTotalQuantity(self, fields) -> None: ...
    def decodeOrderType(self, fields) -> None: ...
    def decodeLmtPrice(self, fields) -> None: ...
    def decodeAuxPrice(self, fields) -> None: ...
    def decodeTIF(self, fields) -> None: ...
    def decodeOcaGroup(self, fields) -> None: ...
    def decodeAccount(self, fields) -> None: ...
    def decodeOpenClose(self, fields) -> None: ...
    def decodeOrigin(self, fields) -> None: ...
    def decodeOrderRef(self, fields) -> None: ...
    def decodeClientId(self, fields) -> None: ...
    def decodePermId(self, fields) -> None: ...
    def decodeOutsideRth(self, fields) -> None: ...
    def decodeHidden(self, fields) -> None: ...
    def decodeDiscretionaryAmt(self, fields) -> None: ...
    def decodeGoodAfterTime(self, fields) -> None: ...
    def skipSharesAllocation(self, fields) -> None: ...
    def decodeFAParams(self, fields) -> None: ...
    def decodeModelCode(self, fields) -> None: ...
    def decodeGoodTillDate(self, fields) -> None: ...
    def decodeRule80A(self, fields) -> None: ...
    def decodePercentOffset(self, fields) -> None: ...
    def decodeSettlingFirm(self, fields) -> None: ...
    def decodeShortSaleParams(self, fields) -> None: ...
    def decodeAuctionStrategy(self, fields) -> None: ...
    def decodeBoxOrderParams(self, fields) -> None: ...
    def decodePegToStkOrVolOrderParams(self, fields) -> None: ...
    def decodeDisplaySize(self, fields) -> None: ...
    def decodeBlockOrder(self, fields) -> None: ...
    def decodeSweepToFill(self, fields) -> None: ...
    def decodeAllOrNone(self, fields) -> None: ...
    def decodeMinQty(self, fields) -> None: ...
    def decodeOcaType(self, fields) -> None: ...
    def skipETradeOnly(self, fields) -> None: ...
    def skipFirmQuoteOnly(self, fields) -> None: ...
    def skipNbboPriceCap(self, fields) -> None: ...
    def decodeParentId(self, fields) -> None: ...
    def decodeTriggerMethod(self, fields) -> None: ...
    def decodeVolOrderParams(self, fields, readOpenOrderAttribs) -> None: ...
    def decodeTrailParams(self, fields) -> None: ...
    def decodeBasisPoints(self, fields) -> None: ...
    def decodeComboLegs(self, fields) -> None: ...
    def decodeSmartComboRoutingParams(self, fields) -> None: ...
    def decodeScaleOrderParams(self, fields) -> None: ...
    def decodeHedgeParams(self, fields) -> None: ...
    def decodeOptOutSmartRouting(self, fields) -> None: ...
    def decodeClearingParams(self, fields) -> None: ...
    def decodeNotHeld(self, fields) -> None: ...
    def decodeDeltaNeutral(self, fields) -> None: ...
    def decodeAlgoParams(self, fields) -> None: ...
    def decodeSolicited(self, fields) -> None: ...
    def decodeOrderStatus(self, fields) -> None: ...
    def decodeWhatIfInfoAndCommission(self, fields) -> None: ...
    def decodeVolRandomizeFlags(self, fields) -> None: ...
    def decodePegToBenchParams(self, fields) -> None: ...
    def decodeConditions(self, fields) -> None: ...
    def decodeAdjustedOrderParams(self, fields) -> None: ...
    def decodeStopPriceAndLmtPriceOffset(self, fields) -> None: ...
    def decodeSoftDollarTier(self, fields) -> None: ...
    def decodeCashQty(self, fields) -> None: ...
    def decodeDontUseAutoPriceForHedge(self, fields) -> None: ...
    def decodeIsOmsContainers(self, fields) -> None: ...
    def decodeDiscretionaryUpToLimitPrice(self, fields) -> None: ...
    def decodeAutoCancelDate(self, fields) -> None: ...
    def decodeFilledQuantity(self, fields) -> None: ...
    def decodeRefFuturesConId(self, fields) -> None: ...
    def decodeAutoCancelParent(self, fields, minVersionAutoCancelParent=...) -> None: ...
    def decodeShareholder(self, fields) -> None: ...
    def decodeImbalanceOnly(self, fields) -> None: ...
    def decodeRouteMarketableToBbo(self, fields) -> None: ...
    def decodeParentPermId(self, fields) -> None: ...
    def decodeCompletedTime(self, fields) -> None: ...
    def decodeCompletedStatus(self, fields) -> None: ...
    def decodeUsePriceMgmtAlgo(self, fields) -> None: ...
    def decodeDuration(self, fields) -> None: ...
    def decodePostToAts(self, fields) -> None: ...
    def decodePegBestPegMidOrderAttributes(self, fields) -> None: ...
    def decodeCustomerAccount(self, fields) -> None: ...
    def decodeProfessionalCustomer(self, fields) -> None: ...
    def decodeBondAccruedInterest(self, fields) -> None: ...
