from ibapi.common import TagValueList as TagValueList
from ibapi.const import UNSET_DOUBLE as UNSET_DOUBLE
from ibapi.contract import ComboLeg as ComboLeg, Contract as Contract, DeltaNeutralContract as DeltaNeutralContract
from ibapi.errors import ERROR_ENCODING_PROTOBUF as ERROR_ENCODING_PROTOBUF
from ibapi.execution import ExecutionFilter as ExecutionFilter
from ibapi.order import Order as Order
from ibapi.order_cancel import OrderCancel as OrderCancel
from ibapi.order_condition import ContractCondition as ContractCondition, Create as Create, ExecutionCondition as ExecutionCondition, MarginCondition as MarginCondition, OperatorCondition as OperatorCondition, OrderCondition as OrderCondition, PercentChangeCondition as PercentChangeCondition, PriceCondition as PriceCondition, TimeCondition as TimeCondition, VolumeCondition as VolumeCondition
from ibapi.protobuf.AllOpenOrdersRequest_pb2 import AllOpenOrdersRequest as AllOpenOrdersRequestProto
from ibapi.protobuf.AutoOpenOrdersRequest_pb2 import AutoOpenOrdersRequest as AutoOpenOrdersRequestProto
from ibapi.protobuf.CancelMarketData_pb2 import CancelMarketData as CancelMarketDataProto
from ibapi.protobuf.CancelMarketDepth_pb2 import CancelMarketDepth as CancelMarketDepthProto
from ibapi.protobuf.CancelOrderRequest_pb2 import CancelOrderRequest as CancelOrderRequestProto
from ibapi.protobuf.ComboLeg_pb2 import ComboLeg as ComboLegProto
from ibapi.protobuf.CompletedOrdersRequest_pb2 import CompletedOrdersRequest as CompletedOrdersRequestProto
from ibapi.protobuf.ContractDataRequest_pb2 import ContractDataRequest as ContractDataRequestProto
from ibapi.protobuf.Contract_pb2 import Contract as ContractProto
from ibapi.protobuf.DeltaNeutralContract_pb2 import DeltaNeutralContract as DeltaNeutralContractProto
from ibapi.protobuf.ExecutionRequest_pb2 import ExecutionRequest as ExecutionRequestProto
from ibapi.protobuf.GlobalCancelRequest_pb2 import GlobalCancelRequest as GlobalCancelRequestProto
from ibapi.protobuf.MarketDataRequest_pb2 import MarketDataRequest as MarketDataRequestProto
from ibapi.protobuf.MarketDataTypeRequest_pb2 import MarketDataTypeRequest as MarketDataTypeRequestProto
from ibapi.protobuf.MarketDepthRequest_pb2 import MarketDepthRequest as MarketDepthRequestProto
from ibapi.protobuf.OpenOrdersRequest_pb2 import OpenOrdersRequest as OpenOrdersRequestProto
from ibapi.protobuf.OrderCancel_pb2 import OrderCancel as OrderCancelProto
from ibapi.protobuf.OrderCondition_pb2 import OrderCondition as OrderConditionProto
from ibapi.protobuf.Order_pb2 import Order as OrderProto
from ibapi.protobuf.PlaceOrderRequest_pb2 import PlaceOrderRequest as PlaceOrderRequestProto
from ibapi.protobuf.SoftDollarTier_pb2 import SoftDollarTier as SoftDollarTierProto
from ibapi.tag_value import TagValue as TagValue
from ibapi.utils import ClientException as ClientException, decimalMaxString as decimalMaxString, isValidDecimalValue as isValidDecimalValue, isValidFloatValue as isValidFloatValue, isValidIntValue as isValidIntValue, isValidLongValue as isValidLongValue

@staticmethod
def createExecutionRequestProto(reqId: int, execFilter: ExecutionFilter) -> ExecutionRequestProto: ...
@staticmethod
def createPlaceOrderRequestProto(orderId: int, contract: Contract, order: Order) -> PlaceOrderRequestProto: ...
@staticmethod
def createContractProto(contract: Contract, order: Order) -> ContractProto: ...
@staticmethod
def createDeltaNeutralContractProto(contract: Contract) -> DeltaNeutralContractProto: ...
@staticmethod
def createComboLegProtoList(contract: Contract, order: Order) -> list[ComboLegProto]: ...
@staticmethod
def createComboLegProto(comboLeg: ComboLeg, perLegPrice: float) -> ComboLegProto: ...
@staticmethod
def createOrderProto(order: Order) -> OrderProto: ...
def createConditionsProto(order: Order) -> list[OrderConditionProto]: ...
@staticmethod
def createOrderConditionProto(orderCondition: OrderCondition) -> OrderConditionProto: ...
@staticmethod
def createOperatorConditionProto(operatorCondition: OperatorCondition) -> OrderConditionProto: ...
@staticmethod
def createContractConditionProto(contractCondition: ContractCondition) -> OrderConditionProto: ...
@staticmethod
def createPriceConditionProto(priceCondition: PriceCondition) -> OrderConditionProto: ...
@staticmethod
def createTimeConditionProto(timeCondition: TimeCondition) -> OrderConditionProto: ...
@staticmethod
def createMarginConditionProto(marginCondition: MarginCondition) -> OrderConditionProto: ...
@staticmethod
def createExecutionConditionProto(executionCondition: ExecutionCondition) -> OrderConditionProto: ...
@staticmethod
def createVolumeConditionProto(volumeCondition: VolumeCondition) -> OrderConditionProto: ...
@staticmethod
def createPercentChangeConditionProto(percentChangeCondition: PercentChangeCondition) -> OrderConditionProto: ...
@staticmethod
def createSoftDollarTierProto(order: Order) -> SoftDollarTierProto: ...
@staticmethod
def fillTagValueList(tagValueList: list, orderProtoMap: dict): ...
@staticmethod
def createCancelOrderRequestProto(orderId: int, orderCancel: OrderCancel) -> CancelOrderRequestProto: ...
@staticmethod
def createGlobalCancelRequestProto(orderCancel: OrderCancel) -> GlobalCancelRequestProto: ...
@staticmethod
def createOrderCancelProto(orderCancel: OrderCancel) -> OrderCancelProto: ...
@staticmethod
def createAllOpenOrdersRequestProto() -> AllOpenOrdersRequestProto: ...
@staticmethod
def createAutoOpenOrdersRequestProto(autoBind: bool) -> AutoOpenOrdersRequestProto: ...
@staticmethod
def createOpenOrdersRequestProto() -> OpenOrdersRequestProto: ...
@staticmethod
def createCompletedOrdersRequestProto(apiOnly: bool) -> CompletedOrdersRequestProto: ...
@staticmethod
def createContractDataRequestProto(reqId: int, contract: Contract) -> ContractDataRequestProto: ...
@staticmethod
def createMarketDataRequestProto(reqId: int, contract: Contract, genericTickList: str, snapshot: bool, regulatorySnapshot: bool, marketDataOptionsList: TagValueList) -> MarketDataRequestProto: ...
@staticmethod
def createMarketDepthRequestProto(reqId: int, contract: Contract, numRows: int, isSmartDepth: bool, marketDepthOptionsList: TagValueList) -> MarketDepthRequestProto: ...
@staticmethod
def createMarketDataTypeRequestProto(marketDataType: int) -> MarketDataTypeRequestProto: ...
@staticmethod
def createCancelMarketDataProto(reqId: int) -> CancelMarketDataProto: ...
@staticmethod
def createCancelMarketDepthProto(reqId: int, isSmartDepth: bool) -> CancelMarketDepthProto: ...
