from ibapi.common import TagValueList as TagValueList, WshEventData as WshEventData
from ibapi.const import UNSET_DOUBLE as UNSET_DOUBLE
from ibapi.contract import ComboLeg as ComboLeg, Contract as Contract, DeltaNeutralContract as DeltaNeutralContract
from ibapi.errors import ERROR_ENCODING_PROTOBUF as ERROR_ENCODING_PROTOBUF
from ibapi.execution import ExecutionFilter as ExecutionFilter
from ibapi.order import Order as Order
from ibapi.order_cancel import OrderCancel as OrderCancel
from ibapi.order_condition import ContractCondition as ContractCondition, Create as Create, ExecutionCondition as ExecutionCondition, MarginCondition as MarginCondition, OperatorCondition as OperatorCondition, OrderCondition as OrderCondition, PercentChangeCondition as PercentChangeCondition, PriceCondition as PriceCondition, TimeCondition as TimeCondition, VolumeCondition as VolumeCondition
from ibapi.protobuf.AccountDataRequest_pb2 import AccountDataRequest as AccountDataRequestProto
from ibapi.protobuf.AccountSummaryRequest_pb2 import AccountSummaryRequest as AccountSummaryRequestProto
from ibapi.protobuf.AccountUpdatesMultiRequest_pb2 import AccountUpdatesMultiRequest as AccountUpdatesMultiRequestProto
from ibapi.protobuf.AllOpenOrdersRequest_pb2 import AllOpenOrdersRequest as AllOpenOrdersRequestProto
from ibapi.protobuf.AutoOpenOrdersRequest_pb2 import AutoOpenOrdersRequest as AutoOpenOrdersRequestProto
from ibapi.protobuf.CalculateImpliedVolatilityRequest_pb2 import CalculateImpliedVolatilityRequest as CalculateImpliedVolatilityRequestProto
from ibapi.protobuf.CalculateOptionPriceRequest_pb2 import CalculateOptionPriceRequest as CalculateOptionPriceRequestProto
from ibapi.protobuf.CancelAccountSummary_pb2 import CancelAccountSummary as CancelAccountSummaryProto
from ibapi.protobuf.CancelAccountUpdatesMulti_pb2 import CancelAccountUpdatesMulti as CancelAccountUpdatesMultiProto
from ibapi.protobuf.CancelCalculateImpliedVolatility_pb2 import CancelCalculateImpliedVolatility as CancelCalculateImpliedVolatilityProto
from ibapi.protobuf.CancelCalculateOptionPrice_pb2 import CancelCalculateOptionPrice as CancelCalculateOptionPriceProto
from ibapi.protobuf.CancelContractData_pb2 import CancelContractData as CancelContractDataProto
from ibapi.protobuf.CancelFundamentalsData_pb2 import CancelFundamentalsData as CancelFundamentalsDataProto
from ibapi.protobuf.CancelHeadTimestamp_pb2 import CancelHeadTimestamp as CancelHeadTimestampProto
from ibapi.protobuf.CancelHistogramData_pb2 import CancelHistogramData as CancelHistogramDataProto
from ibapi.protobuf.CancelHistoricalData_pb2 import CancelHistoricalData as CancelHistoricalDataProto
from ibapi.protobuf.CancelHistoricalTicks_pb2 import CancelHistoricalTicks as CancelHistoricalTicksProto
from ibapi.protobuf.CancelMarketData_pb2 import CancelMarketData as CancelMarketDataProto
from ibapi.protobuf.CancelMarketDepth_pb2 import CancelMarketDepth as CancelMarketDepthProto
from ibapi.protobuf.CancelNewsBulletins_pb2 import CancelNewsBulletins as CancelNewsBulletinsProto
from ibapi.protobuf.CancelOrderRequest_pb2 import CancelOrderRequest as CancelOrderRequestProto
from ibapi.protobuf.CancelPnLSingle_pb2 import CancelPnLSingle as CancelPnLSingleProto
from ibapi.protobuf.CancelPnL_pb2 import CancelPnL as CancelPnLProto
from ibapi.protobuf.CancelPositionsMulti_pb2 import CancelPositionsMulti as CancelPositionsMultiProto
from ibapi.protobuf.CancelPositions_pb2 import CancelPositions as CancelPositionsProto
from ibapi.protobuf.CancelRealTimeBars_pb2 import CancelRealTimeBars as CancelRealTimeBarsProto
from ibapi.protobuf.CancelScannerSubscription_pb2 import CancelScannerSubscription as CancelScannerSubscriptionProto
from ibapi.protobuf.CancelTickByTick_pb2 import CancelTickByTick as CancelTickByTickProto
from ibapi.protobuf.CancelWshEventData_pb2 import CancelWshEventData as CancelWshEventDataProto
from ibapi.protobuf.CancelWshMetaData_pb2 import CancelWshMetaData as CancelWshMetaDataProto
from ibapi.protobuf.ComboLeg_pb2 import ComboLeg as ComboLegProto
from ibapi.protobuf.CompletedOrdersRequest_pb2 import CompletedOrdersRequest as CompletedOrdersRequestProto
from ibapi.protobuf.ContractDataRequest_pb2 import ContractDataRequest as ContractDataRequestProto
from ibapi.protobuf.Contract_pb2 import Contract as ContractProto
from ibapi.protobuf.CurrentTimeInMillisRequest_pb2 import CurrentTimeInMillisRequest as CurrentTimeInMillisRequestProto
from ibapi.protobuf.CurrentTimeRequest_pb2 import CurrentTimeRequest as CurrentTimeRequestProto
from ibapi.protobuf.DeltaNeutralContract_pb2 import DeltaNeutralContract as DeltaNeutralContractProto
from ibapi.protobuf.ExecutionRequest_pb2 import ExecutionRequest as ExecutionRequestProto
from ibapi.protobuf.ExerciseOptionsRequest_pb2 import ExerciseOptionsRequest as ExerciseOptionsRequestProto
from ibapi.protobuf.FAReplace_pb2 import FAReplace as FAReplaceProto
from ibapi.protobuf.FARequest_pb2 import FARequest as FARequestProto
from ibapi.protobuf.FamilyCodesRequest_pb2 import FamilyCodesRequest as FamilyCodesRequestProto
from ibapi.protobuf.FundamentalsDataRequest_pb2 import FundamentalsDataRequest as FundamentalsDataRequestProto
from ibapi.protobuf.GlobalCancelRequest_pb2 import GlobalCancelRequest as GlobalCancelRequestProto
from ibapi.protobuf.HeadTimestampRequest_pb2 import HeadTimestampRequest as HeadTimestampRequestProto
from ibapi.protobuf.HistogramDataRequest_pb2 import HistogramDataRequest as HistogramDataRequestProto
from ibapi.protobuf.HistoricalDataRequest_pb2 import HistoricalDataRequest as HistoricalDataRequestProto
from ibapi.protobuf.HistoricalNewsRequest_pb2 import HistoricalNewsRequest as HistoricalNewsRequestProto
from ibapi.protobuf.HistoricalTicksRequest_pb2 import HistoricalTicksRequest as HistoricalTicksRequestProto
from ibapi.protobuf.IdsRequest_pb2 import IdsRequest as IdsRequestProto
from ibapi.protobuf.ManagedAccountsRequest_pb2 import ManagedAccountsRequest as ManagedAccountsRequestProto
from ibapi.protobuf.MarketDataRequest_pb2 import MarketDataRequest as MarketDataRequestProto
from ibapi.protobuf.MarketDataTypeRequest_pb2 import MarketDataTypeRequest as MarketDataTypeRequestProto
from ibapi.protobuf.MarketDepthExchangesRequest_pb2 import MarketDepthExchangesRequest as MarketDepthExchangesRequestProto
from ibapi.protobuf.MarketDepthRequest_pb2 import MarketDepthRequest as MarketDepthRequestProto
from ibapi.protobuf.MarketRuleRequest_pb2 import MarketRuleRequest as MarketRuleRequestProto
from ibapi.protobuf.MatchingSymbolsRequest_pb2 import MatchingSymbolsRequest as MatchingSymbolsRequestProto
from ibapi.protobuf.NewsArticleRequest_pb2 import NewsArticleRequest as NewsArticleRequestProto
from ibapi.protobuf.NewsBulletinsRequest_pb2 import NewsBulletinsRequest as NewsBulletinsRequestProto
from ibapi.protobuf.NewsProvidersRequest_pb2 import NewsProvidersRequest as NewsProvidersRequestProto
from ibapi.protobuf.OpenOrdersRequest_pb2 import OpenOrdersRequest as OpenOrdersRequestProto
from ibapi.protobuf.OrderCancel_pb2 import OrderCancel as OrderCancelProto
from ibapi.protobuf.OrderCondition_pb2 import OrderCondition as OrderConditionProto
from ibapi.protobuf.Order_pb2 import Order as OrderProto
from ibapi.protobuf.PlaceOrderRequest_pb2 import PlaceOrderRequest as PlaceOrderRequestProto
from ibapi.protobuf.PnLRequest_pb2 import PnLRequest as PnLRequestProto
from ibapi.protobuf.PnLSingleRequest_pb2 import PnLSingleRequest as PnLSingleRequestProto
from ibapi.protobuf.PositionsMultiRequest_pb2 import PositionsMultiRequest as PositionsMultiRequestProto
from ibapi.protobuf.PositionsRequest_pb2 import PositionsRequest as PositionsRequestProto
from ibapi.protobuf.QueryDisplayGroupsRequest_pb2 import QueryDisplayGroupsRequest as QueryDisplayGroupsRequestProto
from ibapi.protobuf.RealTimeBarsRequest_pb2 import RealTimeBarsRequest as RealTimeBarsRequestProto
from ibapi.protobuf.ScannerParametersRequest_pb2 import ScannerParametersRequest as ScannerParametersRequestProto
from ibapi.protobuf.ScannerSubscriptionRequest_pb2 import ScannerSubscriptionRequest as ScannerSubscriptionRequestProto
from ibapi.protobuf.ScannerSubscription_pb2 import ScannerSubscription as ScannerSubscriptionProto
from ibapi.protobuf.SecDefOptParamsRequest_pb2 import SecDefOptParamsRequest as SecDefOptParamsRequestProto
from ibapi.protobuf.SetServerLogLevelRequest_pb2 import SetServerLogLevelRequest as SetServerLogLevelRequestProto
from ibapi.protobuf.SmartComponentsRequest_pb2 import SmartComponentsRequest as SmartComponentsRequestProto
from ibapi.protobuf.SoftDollarTier_pb2 import SoftDollarTier as SoftDollarTierProto
from ibapi.protobuf.SoftDollarTiersRequest_pb2 import SoftDollarTiersRequest as SoftDollarTiersRequestProto
from ibapi.protobuf.StartApiRequest_pb2 import StartApiRequest as StartApiRequestProto
from ibapi.protobuf.SubscribeToGroupEventsRequest_pb2 import SubscribeToGroupEventsRequest as SubscribeToGroupEventsRequestProto
from ibapi.protobuf.TickByTickRequest_pb2 import TickByTickRequest as TickByTickRequestProto
from ibapi.protobuf.UnsubscribeFromGroupEventsRequest_pb2 import UnsubscribeFromGroupEventsRequest as UnsubscribeFromGroupEventsRequestProto
from ibapi.protobuf.UpdateDisplayGroupRequest_pb2 import UpdateDisplayGroupRequest as UpdateDisplayGroupRequestProto
from ibapi.protobuf.UserInfoRequest_pb2 import UserInfoRequest as UserInfoRequestProto
from ibapi.protobuf.VerifyMessageRequest_pb2 import VerifyMessageRequest as VerifyMessageRequestProto
from ibapi.protobuf.VerifyRequest_pb2 import VerifyRequest as VerifyRequestProto
from ibapi.protobuf.WshEventDataRequest_pb2 import WshEventDataRequest as WshEventDataRequestProto
from ibapi.protobuf.WshMetaDataRequest_pb2 import WshMetaDataRequest as WshMetaDataRequestProto
from ibapi.scanner import ScannerSubscription as ScannerSubscription
from ibapi.tag_value import TagValue as TagValue
from ibapi.utils import ClientException as ClientException, decimalMaxString as decimalMaxString, isValidDecimalValue as isValidDecimalValue, isValidFloatValue as isValidFloatValue, isValidIntValue as isValidIntValue, isValidLongValue as isValidLongValue

@staticmethod
def createExecutionRequestProto(reqId: int, execFilter: ExecutionFilter) -> ExecutionRequestProto: ...
@staticmethod
def createPlaceOrderRequestProto(orderId: int, contract: Contract, order: Order) -> PlaceOrderRequestProto: ...
@staticmethod
def createContractProto(contract: Contract, order: Order) -> ContractProto: ...
@staticmethod
def createDeltaNeutralContractProto(contract: Contract) -> DeltaNeutralContractProto: ...
@staticmethod
def createComboLegProtoList(contract: Contract, order: Order) -> list[ComboLegProto]: ...
@staticmethod
def createComboLegProto(comboLeg: ComboLeg, perLegPrice: float) -> ComboLegProto: ...
@staticmethod
def createOrderProto(order: Order) -> OrderProto: ...
def createConditionsProto(order: Order) -> list[OrderConditionProto]: ...
@staticmethod
def createOrderConditionProto(orderCondition: OrderCondition) -> OrderConditionProto: ...
@staticmethod
def createOperatorConditionProto(operatorCondition: OperatorCondition) -> OrderConditionProto: ...
@staticmethod
def createContractConditionProto(contractCondition: ContractCondition) -> OrderConditionProto: ...
@staticmethod
def createPriceConditionProto(priceCondition: PriceCondition) -> OrderConditionProto: ...
@staticmethod
def createTimeConditionProto(timeCondition: TimeCondition) -> OrderConditionProto: ...
@staticmethod
def createMarginConditionProto(marginCondition: MarginCondition) -> OrderConditionProto: ...
@staticmethod
def createExecutionConditionProto(executionCondition: ExecutionCondition) -> OrderConditionProto: ...
@staticmethod
def createVolumeConditionProto(volumeCondition: VolumeCondition) -> OrderConditionProto: ...
@staticmethod
def createPercentChangeConditionProto(percentChangeCondition: PercentChangeCondition) -> OrderConditionProto: ...
@staticmethod
def createSoftDollarTierProto(order: Order) -> SoftDollarTierProto: ...
@staticmethod
def fillTagValueList(tagValueList: list, orderProtoMap: dict): ...
@staticmethod
def createCancelOrderRequestProto(orderId: int, orderCancel: OrderCancel) -> CancelOrderRequestProto: ...
@staticmethod
def createGlobalCancelRequestProto(orderCancel: OrderCancel) -> GlobalCancelRequestProto: ...
@staticmethod
def createOrderCancelProto(orderCancel: OrderCancel) -> OrderCancelProto: ...
@staticmethod
def createAllOpenOrdersRequestProto() -> AllOpenOrdersRequestProto: ...
@staticmethod
def createAutoOpenOrdersRequestProto(autoBind: bool) -> AutoOpenOrdersRequestProto: ...
@staticmethod
def createOpenOrdersRequestProto() -> OpenOrdersRequestProto: ...
@staticmethod
def createCompletedOrdersRequestProto(apiOnly: bool) -> CompletedOrdersRequestProto: ...
@staticmethod
def createContractDataRequestProto(reqId: int, contract: Contract) -> ContractDataRequestProto: ...
@staticmethod
def createMarketDataRequestProto(reqId: int, contract: Contract, genericTickList: str, snapshot: bool, regulatorySnapshot: bool, marketDataOptionsList: TagValueList) -> MarketDataRequestProto: ...
@staticmethod
def createMarketDepthRequestProto(reqId: int, contract: Contract, numRows: int, isSmartDepth: bool, marketDepthOptionsList: TagValueList) -> MarketDepthRequestProto: ...
@staticmethod
def createMarketDataTypeRequestProto(marketDataType: int) -> MarketDataTypeRequestProto: ...
@staticmethod
def createCancelMarketDataProto(reqId: int) -> CancelMarketDataProto: ...
@staticmethod
def createCancelMarketDepthProto(reqId: int, isSmartDepth: bool) -> CancelMarketDepthProto: ...
@staticmethod
def createAccountDataRequestProto(subscribe: bool, acctCode: str) -> AccountDataRequestProto: ...
@staticmethod
def createManagedAccountsRequestProto() -> ManagedAccountsRequestProto: ...
@staticmethod
def createPositionsRequestProto() -> PositionsRequestProto: ...
@staticmethod
def createCancelPositionsRequestProto() -> CancelPositionsProto: ...
@staticmethod
def createAccountSummaryRequestProto(reqId: int, group: str, tags: str) -> AccountSummaryRequestProto: ...
@staticmethod
def createCancelAccountSummaryRequestProto(reqId: int) -> CancelAccountSummaryProto: ...
@staticmethod
def createPositionsMultiRequestProto(reqId: int, account: str, modelCode: str) -> PositionsMultiRequestProto: ...
@staticmethod
def createCancelPositionsMultiRequestProto(reqId: int) -> CancelPositionsMultiProto: ...
@staticmethod
def createAccountUpdatesMultiRequestProto(reqId: int, account: str, modelCode: str, ledgerAndNLV: bool) -> AccountUpdatesMultiRequestProto: ...
@staticmethod
def createCancelAccountUpdatesMultiRequestProto(reqId: int) -> CancelAccountUpdatesMultiProto: ...
@staticmethod
def createHistoricalDataRequestProto(reqId: int, contract: Contract, endDateTime: str, duration: str, barSizeSetting: str, whatToShow: str, useRTH: bool, formatDate: int, keepUpToDate: bool, chartOptionsList: TagValueList) -> HistoricalDataRequestProto: ...
@staticmethod
def createRealTimeBarsRequestProto(reqId: int, contract: Contract, barSize: int, whatToShow: str, useRTH: bool, realTimeBarsOptionsList: TagValueList) -> RealTimeBarsRequestProto: ...
@staticmethod
def createHeadTimestampRequestProto(reqId: int, contract: Contract, whatToShow: str, useRTH: bool, formatDate: int) -> HeadTimestampRequestProto: ...
@staticmethod
def createHistogramDataRequestProto(reqId: int, contract: Contract, useRTH: bool, timePeriod: str) -> HistogramDataRequestProto: ...
@staticmethod
def createHistoricalTicksRequestProto(reqId: int, contract: Contract, startDateTime: str, endDateTime: str, numberOfTicks: int, whatToShow: str, useRTH: bool, ignoreSize: bool, miscOptionsList: TagValueList) -> HistoricalTicksRequestProto: ...
@staticmethod
def createTickByTickRequestProto(reqId: int, contract: Contract, tickType: str, numberOfTicks: int, ignoreSize: bool) -> TickByTickRequestProto: ...
@staticmethod
def createCancelHistoricalDataProto(reqId: int) -> CancelHistoricalDataProto: ...
@staticmethod
def createCancelRealTimeBarsProto(reqId: int) -> CancelRealTimeBarsProto: ...
@staticmethod
def createCancelHeadTimestampProto(reqId: int) -> CancelHeadTimestampProto: ...
@staticmethod
def createCancelHistogramDataProto(reqId: int) -> CancelHistogramDataProto: ...
@staticmethod
def createCancelTickByTickProto(reqId: int) -> CancelTickByTickProto: ...
@staticmethod
def createNewsBulletinsRequestProto(allMessages: bool) -> NewsBulletinsRequestProto: ...
@staticmethod
def createCancelNewsBulletinsProto() -> CancelNewsBulletinsProto: ...
@staticmethod
def createNewsArticleRequestProto(reqId: int, providerCode: str, articleId: str, newsArticleOptionsList: TagValueList) -> NewsArticleRequestProto: ...
@staticmethod
def createNewsProvidersRequestProto() -> NewsProvidersRequestProto: ...
@staticmethod
def createHistoricalNewsRequestProto(reqId: int, conId: int, providerCodes: str, startDateTime: str, endDateTime: str, totalResults: int, historicalNewsOptionsList: TagValueList) -> HistoricalNewsRequestProto: ...
@staticmethod
def createWshMetaDataRequestProto(reqId: int) -> WshMetaDataRequestProto: ...
@staticmethod
def createCancelWshMetaDataProto(reqId: int) -> CancelWshMetaDataProto: ...
@staticmethod
def createWshEventDataRequestProto(reqId: int, wshEventData: WshEventData) -> WshEventDataRequestProto: ...
@staticmethod
def createCancelWshEventDataProto(reqId: int) -> CancelWshEventDataProto: ...
@staticmethod
def createScannerParametersRequestProto() -> ScannerParametersRequestProto: ...
@staticmethod
def createScannerSubscriptionRequestProto(reqId: int, subscription: ScannerSubscription, scannerSubscriptionOptionsList: TagValueList, scannerSubscriptionFilterOptionsList: TagValueList) -> ScannerSubscriptionRequestProto: ...
@staticmethod
def createScannerSubscriptionProto(subscription: ScannerSubscription, scannerSubscriptionOptionsList: TagValueList, scannerSubscriptionFilterOptionsList: TagValueList) -> ScannerSubscriptionProto: ...
@staticmethod
def createFundamentalsDataRequestProto(reqId: int, contract: Contract, reportType: str, fundamentalsDataOptionsList: TagValueList) -> FundamentalsDataRequestProto: ...
@staticmethod
def createPnLRequestProto(reqId: int, account: str, modelCode: str) -> PnLRequestProto: ...
@staticmethod
def createPnLSingleRequestProto(reqId: int, account: str, modelCode: str, conId: int) -> PnLSingleRequestProto: ...
@staticmethod
def createCancelScannerSubscriptionProto(reqId: int) -> CancelScannerSubscriptionProto: ...
@staticmethod
def createCancelFundamentalsDataProto(reqId: int) -> CancelFundamentalsDataProto: ...
@staticmethod
def createCancelPnLProto(reqId: int) -> CancelPnLProto: ...
@staticmethod
def createCancelPnLSingleProto(reqId: int) -> CancelPnLSingleProto: ...
@staticmethod
def createFARequestProto(faDataType: int) -> FARequestProto: ...
@staticmethod
def createFAReplaceProto(reqId: int, faDataType: int, xml: str) -> FAReplaceProto: ...
@staticmethod
def createExerciseOptionsRequestProto(orderId: int, contract: Contract, exerciseAction: int, exerciseQuantity: int, account: str, override: bool, manualOrderTime: str, customerAccount: str, professionalCustomer: bool) -> ExerciseOptionsRequestProto: ...
@staticmethod
def createCalculateImpliedVolatilityRequestProto(reqId: int, contract: Contract, optionPrice: float, underPrice: float, impliedVolatilityOptionsList: TagValueList) -> CalculateImpliedVolatilityRequestProto: ...
@staticmethod
def createCancelCalculateImpliedVolatilityProto(reqId: int) -> CancelCalculateImpliedVolatilityProto: ...
@staticmethod
def createCalculateOptionPriceRequestProto(reqId: int, contract: Contract, volatility: float, underPrice: float, optionPriceOptionsList: TagValueList) -> CalculateOptionPriceRequestProto: ...
@staticmethod
def createCancelCalculateOptionPriceProto(reqId: int) -> CancelCalculateOptionPriceProto: ...
@staticmethod
def createSecDefOptParamsRequestProto(reqId: int, underlyingSymbol: str, futFopExchange: str, underlyingSecType: str, underlyingConId: int) -> SecDefOptParamsRequestProto: ...
@staticmethod
def createSoftDollarTiersRequestProto(reqId: int) -> SoftDollarTiersRequestProto: ...
@staticmethod
def createFamilyCodesRequestProto() -> FamilyCodesRequestProto: ...
@staticmethod
def createMatchingSymbolsRequestProto(reqId: int, pattern: str) -> MatchingSymbolsRequestProto: ...
@staticmethod
def createSmartComponentsRequestProto(reqId: int, bboExchange: str) -> SmartComponentsRequestProto: ...
@staticmethod
def createMarketRuleRequestProto(marketRuleId: int) -> MarketRuleRequestProto: ...
@staticmethod
def createUserInfoRequestProto(reqId: int) -> UserInfoRequestProto: ...
@staticmethod
def createIdsRequestProto(numIds: int) -> IdsRequestProto: ...
@staticmethod
def createCurrentTimeRequestProto() -> CurrentTimeRequestProto: ...
@staticmethod
def createCurrentTimeInMillisRequestProto() -> CurrentTimeInMillisRequestProto: ...
@staticmethod
def createStartApiRequestProto(clientId: int, optionalCapabilities: str) -> StartApiRequestProto: ...
@staticmethod
def createSetServerLogLevelRequestProto(logLevel: int) -> SetServerLogLevelRequestProto: ...
@staticmethod
def createVerifyRequestProto(apiName: str, apiVersion: str) -> VerifyRequestProto: ...
@staticmethod
def createVerifyMessageRequestProto(apiData: str) -> VerifyMessageRequestProto: ...
@staticmethod
def createQueryDisplayGroupsRequestProto(reqId: int) -> QueryDisplayGroupsRequestProto: ...
@staticmethod
def createSubscribeToGroupEventsRequestProto(reqId: int, groupId: int) -> SubscribeToGroupEventsRequestProto: ...
@staticmethod
def createUpdateDisplayGroupRequestProto(reqId: int, contractInfo: str) -> UpdateDisplayGroupRequestProto: ...
@staticmethod
def createUnsubscribeFromGroupEventsRequestProto(reqId: int) -> UnsubscribeFromGroupEventsRequestProto: ...
@staticmethod
def createMarketDepthExchangesRequestProto() -> MarketDepthExchangesRequestProto: ...
@staticmethod
def createCancelContractDataProto(reqId: int) -> CancelContractDataProto: ...
@staticmethod
def createCancelHistoricalTicksProto(reqId: int) -> CancelHistoricalTicksProto: ...
