from ibapi.const import UNSET_DOUBLE as UNSET_DOUBLE
from ibapi.contract import ComboLeg as ComboLeg, Contract as Contract, DeltaNeutralContract as DeltaNeutralContract
from ibapi.execution import ExecutionFilter as ExecutionFilter
from ibapi.order import Order as Order
from ibapi.order_condition import ContractCondition as ContractCondition, Create as Create, ExecutionCondition as ExecutionCondition, MarginCondition as MarginCondition, OperatorCondition as OperatorCondition, OrderCondition as OrderCondition, PercentChangeCondition as PercentChangeCondition, PriceCondition as PriceCondition, TimeCondition as TimeCondition, VolumeCondition as VolumeCondition
from ibapi.protobuf.CancelOrderRequest_pb2 import CancelOrderRequest as CancelOrderRequestProto
from ibapi.protobuf.ComboLeg_pb2 import ComboLeg as ComboLegProto
from ibapi.protobuf.Contract_pb2 import Contract as ContractProto
from ibapi.protobuf.DeltaNeutralContract_pb2 import DeltaNeutralContract as DeltaNeutralContractProto
from ibapi.protobuf.ExecutionRequest_pb2 import ExecutionRequest as ExecutionRequestProto
from ibapi.protobuf.GlobalCancelRequest_pb2 import GlobalCancelRequest as GlobalCancelRequestProto
from ibapi.protobuf.OrderCancel_pb2 import OrderCancel as OrderCancelProto
from ibapi.protobuf.OrderCondition_pb2 import OrderCondition as OrderConditionProto
from ibapi.protobuf.Order_pb2 import Order as OrderProto
from ibapi.protobuf.PlaceOrderRequest_pb2 import PlaceOrderRequest as PlaceOrderRequestProto
from ibapi.protobuf.SoftDollarTier_pb2 import SoftDollarTier as SoftDollarTierProto
from ibapi.tag_value import TagValue as TagValue
from ibapi.utils import decimalMaxString as decimalMaxString, isValidDecimalValue as isValidDecimalValue, isValidFloatValue as isValidFloatValue, isValidIntValue as isValidIntValue, isValidLongValue as isValidLongValue

@staticmethod
def createExecutionRequestProto(reqId: int, execFilter: ExecutionFilter) -> ExecutionRequestProto: ...
@staticmethod
def createPlaceOrderRequestProto(orderId: int, contract: Contract, order: Order) -> PlaceOrderRequestProto: ...
@staticmethod
def createContractProto(contract: Contract, order: Order) -> ContractProto: ...
@staticmethod
def createDeltaNeutralContractProto(contract: Contract) -> DeltaNeutralContractProto: ...
@staticmethod
def createComboLegProtoList(contract: Contract, order: Order) -> list[ComboLegProto]: ...
@staticmethod
def createComboLegProto(comboLeg: ComboLeg, perLegPrice: float) -> ComboLegProto: ...
@staticmethod
def createOrderProto(order: Order) -> OrderProto: ...
def createConditionsProto(order: Order) -> list[OrderConditionProto]: ...
@staticmethod
def createOrderConditionProto(orderCondition: OrderCondition) -> OrderConditionProto: ...
@staticmethod
def createOperatorConditionProto(operatorCondition: OperatorCondition) -> OrderConditionProto: ...
@staticmethod
def createContractConditionProto(contractCondition: ContractCondition) -> OrderConditionProto: ...
@staticmethod
def createPriceConditionProto(priceCondition: PriceCondition) -> OrderConditionProto: ...
@staticmethod
def createTimeConditionProto(timeCondition: TimeCondition) -> OrderConditionProto: ...
@staticmethod
def createMarginConditionProto(marginCondition: MarginCondition) -> OrderConditionProto: ...
@staticmethod
def createExecutionConditionProto(executionCondition: ExecutionCondition) -> OrderConditionProto: ...
@staticmethod
def createVolumeConditionProto(volumeCondition: VolumeCondition) -> OrderConditionProto: ...
@staticmethod
def createPercentChangeConditionProto(percentChangeCondition: PercentChangeCondition) -> OrderConditionProto: ...
@staticmethod
def createSoftDollarTierProto(order: Order) -> SoftDollarTierProto: ...
@staticmethod
def fillTagValueList(tagValueList: list, orderProtoMap: dict): ...
@staticmethod
def createCancelOrderRequestProto(orderId: int, orderCancel: OrderCancelProto) -> CancelOrderRequestProto: ...
@staticmethod
def createGlobalCancelRequestProto(orderCancel: OrderCancelProto) -> GlobalCancelRequestProto: ...
@staticmethod
def createOrderCancelProto(orderCancel: OrderCancelProto) -> OrderCancelProto: ...
