from ibapi.common import *
from _typeshed import Incomplete
from ibapi import comm as comm, decoder as decoder, reader as reader
from ibapi.client_utils import createAccountDataRequestProto as createAccountDataRequestProto, createAccountSummaryRequestProto as createAccountSummaryRequestProto, createAccountUpdatesMultiRequestProto as createAccountUpdatesMultiRequestProto, createAllOpenOrdersRequestProto as createAllOpenOrdersRequestProto, createAutoOpenOrdersRequestProto as createAutoOpenOrdersRequestProto, createCalculateImpliedVolatilityRequestProto as createCalculateImpliedVolatilityRequestProto, createCalculateOptionPriceRequestProto as createCalculateOptionPriceRequestProto, createCancelAccountSummaryRequestProto as createCancelAccountSummaryRequestProto, createCancelAccountUpdatesMultiRequestProto as createCancelAccountUpdatesMultiRequestProto, createCancelCalculateImpliedVolatilityProto as createCancelCalculateImpliedVolatilityProto, createCancelCalculateOptionPriceProto as createCancelCalculateOptionPriceProto, createCancelContractDataProto as createCancelContractDataProto, createCancelFundamentalsDataProto as createCancelFundamentalsDataProto, createCancelHeadTimestampProto as createCancelHeadTimestampProto, createCancelHistogramDataProto as createCancelHistogramDataProto, createCancelHistoricalDataProto as createCancelHistoricalDataProto, createCancelHistoricalTicksProto as createCancelHistoricalTicksProto, createCancelMarketDataProto as createCancelMarketDataProto, createCancelMarketDepthProto as createCancelMarketDepthProto, createCancelNewsBulletinsProto as createCancelNewsBulletinsProto, createCancelOrderRequestProto as createCancelOrderRequestProto, createCancelPnLProto as createCancelPnLProto, createCancelPnLSingleProto as createCancelPnLSingleProto, createCancelPositionsMultiRequestProto as createCancelPositionsMultiRequestProto, createCancelPositionsRequestProto as createCancelPositionsRequestProto, createCancelRealTimeBarsProto as createCancelRealTimeBarsProto, createCancelScannerSubscriptionProto as createCancelScannerSubscriptionProto, createCancelTickByTickProto as createCancelTickByTickProto, createCancelWshEventDataProto as createCancelWshEventDataProto, createCancelWshMetaDataProto as createCancelWshMetaDataProto, createCompletedOrdersRequestProto as createCompletedOrdersRequestProto, createContractDataRequestProto as createContractDataRequestProto, createCurrentTimeInMillisRequestProto as createCurrentTimeInMillisRequestProto, createCurrentTimeRequestProto as createCurrentTimeRequestProto, createExecutionRequestProto as createExecutionRequestProto, createExerciseOptionsRequestProto as createExerciseOptionsRequestProto, createFAReplaceProto as createFAReplaceProto, createFARequestProto as createFARequestProto, createFamilyCodesRequestProto as createFamilyCodesRequestProto, createFundamentalsDataRequestProto as createFundamentalsDataRequestProto, createGlobalCancelRequestProto as createGlobalCancelRequestProto, createHeadTimestampRequestProto as createHeadTimestampRequestProto, createHistogramDataRequestProto as createHistogramDataRequestProto, createHistoricalDataRequestProto as createHistoricalDataRequestProto, createHistoricalNewsRequestProto as createHistoricalNewsRequestProto, createHistoricalTicksRequestProto as createHistoricalTicksRequestProto, createIdsRequestProto as createIdsRequestProto, createManagedAccountsRequestProto as createManagedAccountsRequestProto, createMarketDataRequestProto as createMarketDataRequestProto, createMarketDataTypeRequestProto as createMarketDataTypeRequestProto, createMarketDepthExchangesRequestProto as createMarketDepthExchangesRequestProto, createMarketDepthRequestProto as createMarketDepthRequestProto, createMarketRuleRequestProto as createMarketRuleRequestProto, createMatchingSymbolsRequestProto as createMatchingSymbolsRequestProto, createNewsArticleRequestProto as createNewsArticleRequestProto, createNewsBulletinsRequestProto as createNewsBulletinsRequestProto, createNewsProvidersRequestProto as createNewsProvidersRequestProto, createOpenOrdersRequestProto as createOpenOrdersRequestProto, createPlaceOrderRequestProto as createPlaceOrderRequestProto, createPnLRequestProto as createPnLRequestProto, createPnLSingleRequestProto as createPnLSingleRequestProto, createPositionsMultiRequestProto as createPositionsMultiRequestProto, createPositionsRequestProto as createPositionsRequestProto, createQueryDisplayGroupsRequestProto as createQueryDisplayGroupsRequestProto, createRealTimeBarsRequestProto as createRealTimeBarsRequestProto, createScannerParametersRequestProto as createScannerParametersRequestProto, createScannerSubscriptionRequestProto as createScannerSubscriptionRequestProto, createSecDefOptParamsRequestProto as createSecDefOptParamsRequestProto, createSetServerLogLevelRequestProto as createSetServerLogLevelRequestProto, createSmartComponentsRequestProto as createSmartComponentsRequestProto, createSoftDollarTiersRequestProto as createSoftDollarTiersRequestProto, createStartApiRequestProto as createStartApiRequestProto, createSubscribeToGroupEventsRequestProto as createSubscribeToGroupEventsRequestProto, createTickByTickRequestProto as createTickByTickRequestProto, createUnsubscribeFromGroupEventsRequestProto as createUnsubscribeFromGroupEventsRequestProto, createUpdateDisplayGroupRequestProto as createUpdateDisplayGroupRequestProto, createUserInfoRequestProto as createUserInfoRequestProto, createVerifyMessageRequestProto as createVerifyMessageRequestProto, createVerifyRequestProto as createVerifyRequestProto, createWshEventDataRequestProto as createWshEventDataRequestProto, createWshMetaDataRequestProto as createWshMetaDataRequestProto
from ibapi.comm import make_field as make_field, make_field_handle_empty as make_field_handle_empty
from ibapi.common import PROTOBUF_MSG_ID as PROTOBUF_MSG_ID
from ibapi.connection import Connection as Connection
from ibapi.const import MAX_MSG_LEN as MAX_MSG_LEN, NO_VALID_ID as NO_VALID_ID, UNSET_DOUBLE as UNSET_DOUBLE
from ibapi.contract import Contract as Contract
from ibapi.errors import ALREADY_CONNECTED as ALREADY_CONNECTED, BAD_LENGTH as BAD_LENGTH, CONNECT_FAIL as CONNECT_FAIL, FAIL_SEND_ACCT as FAIL_SEND_ACCT, FAIL_SEND_CANACCOUNTDATA as FAIL_SEND_CANACCOUNTDATA, FAIL_SEND_CANACCOUNTUPDATESMULTI as FAIL_SEND_CANACCOUNTUPDATESMULTI, FAIL_SEND_CANCALCIMPLIEDVOLAT as FAIL_SEND_CANCALCIMPLIEDVOLAT, FAIL_SEND_CANCALCOPTIONPRICE as FAIL_SEND_CANCALCOPTIONPRICE, FAIL_SEND_CANCELHEADTIMESTAMP as FAIL_SEND_CANCELHEADTIMESTAMP, FAIL_SEND_CANCELHISTOGRAMDATA as FAIL_SEND_CANCELHISTOGRAMDATA, FAIL_SEND_CANCELPNL as FAIL_SEND_CANCELPNL, FAIL_SEND_CANCELPNLSINGLE as FAIL_SEND_CANCELPNLSINGLE, FAIL_SEND_CANCELTICKBYTICKDATA as FAIL_SEND_CANCELTICKBYTICKDATA, FAIL_SEND_CANCEL_CONTRACT_DATA as FAIL_SEND_CANCEL_CONTRACT_DATA, FAIL_SEND_CANCEL_HISTORICAL_TICKS as FAIL_SEND_CANCEL_HISTORICAL_TICKS, FAIL_SEND_CANFUNDDATA as FAIL_SEND_CANFUNDDATA, FAIL_SEND_CANHISTDATA as FAIL_SEND_CANHISTDATA, FAIL_SEND_CANMKT as FAIL_SEND_CANMKT, FAIL_SEND_CANMKTDEPTH as FAIL_SEND_CANMKTDEPTH, FAIL_SEND_CANPOSITIONS as FAIL_SEND_CANPOSITIONS, FAIL_SEND_CANPOSITIONSMULTI as FAIL_SEND_CANPOSITIONSMULTI, FAIL_SEND_CANRTBARS as FAIL_SEND_CANRTBARS, FAIL_SEND_CANSCANNER as FAIL_SEND_CANSCANNER, FAIL_SEND_CAN_WSH_EVENT_DATA as FAIL_SEND_CAN_WSH_EVENT_DATA, FAIL_SEND_CAN_WSH_META_DATA as FAIL_SEND_CAN_WSH_META_DATA, FAIL_SEND_CORDER as FAIL_SEND_CORDER, FAIL_SEND_EXEC as FAIL_SEND_EXEC, FAIL_SEND_FA_REPLACE as FAIL_SEND_FA_REPLACE, FAIL_SEND_FA_REQUEST as FAIL_SEND_FA_REQUEST, FAIL_SEND_OORDER as FAIL_SEND_OORDER, FAIL_SEND_ORDER as FAIL_SEND_ORDER, FAIL_SEND_QUERYDISPLAYGROUPS as FAIL_SEND_QUERYDISPLAYGROUPS, FAIL_SEND_REQACCOUNTDATA as FAIL_SEND_REQACCOUNTDATA, FAIL_SEND_REQACCOUNTUPDATESMULTI as FAIL_SEND_REQACCOUNTUPDATESMULTI, FAIL_SEND_REQCALCIMPLIEDVOLAT as FAIL_SEND_REQCALCIMPLIEDVOLAT, FAIL_SEND_REQCALCOPTIONPRICE as FAIL_SEND_REQCALCOPTIONPRICE, FAIL_SEND_REQCOMPLETEDORDERS as FAIL_SEND_REQCOMPLETEDORDERS, FAIL_SEND_REQCONTRACT as FAIL_SEND_REQCONTRACT, FAIL_SEND_REQCURRTIME as FAIL_SEND_REQCURRTIME, FAIL_SEND_REQCURRTIMEINMILLIS as FAIL_SEND_REQCURRTIMEINMILLIS, FAIL_SEND_REQFAMILYCODES as FAIL_SEND_REQFAMILYCODES, FAIL_SEND_REQFUNDDATA as FAIL_SEND_REQFUNDDATA, FAIL_SEND_REQGLOBALCANCEL as FAIL_SEND_REQGLOBALCANCEL, FAIL_SEND_REQHEADTIMESTAMP as FAIL_SEND_REQHEADTIMESTAMP, FAIL_SEND_REQHISTDATA as FAIL_SEND_REQHISTDATA, FAIL_SEND_REQHISTOGRAMDATA as FAIL_SEND_REQHISTOGRAMDATA, FAIL_SEND_REQHISTORICALNEWS as FAIL_SEND_REQHISTORICALNEWS, FAIL_SEND_REQHISTORICALTICKS as FAIL_SEND_REQHISTORICALTICKS, FAIL_SEND_REQMARKETDATATYPE as FAIL_SEND_REQMARKETDATATYPE, FAIL_SEND_REQMARKETRULE as FAIL_SEND_REQMARKETRULE, FAIL_SEND_REQMATCHINGSYMBOLS as FAIL_SEND_REQMATCHINGSYMBOLS, FAIL_SEND_REQMKT as FAIL_SEND_REQMKT, FAIL_SEND_REQMKTDEPTH as FAIL_SEND_REQMKTDEPTH, FAIL_SEND_REQMKTDEPTHEXCHANGES as FAIL_SEND_REQMKTDEPTHEXCHANGES, FAIL_SEND_REQNEWSARTICLE as FAIL_SEND_REQNEWSARTICLE, FAIL_SEND_REQNEWSPROVIDERS as FAIL_SEND_REQNEWSPROVIDERS, FAIL_SEND_REQPNL as FAIL_SEND_REQPNL, FAIL_SEND_REQPNLSINGLE as FAIL_SEND_REQPNLSINGLE, FAIL_SEND_REQPOSITIONS as FAIL_SEND_REQPOSITIONS, FAIL_SEND_REQPOSITIONSMULTI as FAIL_SEND_REQPOSITIONSMULTI, FAIL_SEND_REQRTBARS as FAIL_SEND_REQRTBARS, FAIL_SEND_REQSCANNER as FAIL_SEND_REQSCANNER, FAIL_SEND_REQSCANNERPARAMETERS as FAIL_SEND_REQSCANNERPARAMETERS, FAIL_SEND_REQSECDEFOPTPARAMS as FAIL_SEND_REQSECDEFOPTPARAMS, FAIL_SEND_REQSMARTCOMPONENTS as FAIL_SEND_REQSMARTCOMPONENTS, FAIL_SEND_REQSOFTDOLLARTIERS as FAIL_SEND_REQSOFTDOLLARTIERS, FAIL_SEND_REQTICKBYTICKDATA as FAIL_SEND_REQTICKBYTICKDATA, FAIL_SEND_REQ_USER_INFO as FAIL_SEND_REQ_USER_INFO, FAIL_SEND_REQ_WSH_EVENT_DATA as FAIL_SEND_REQ_WSH_EVENT_DATA, FAIL_SEND_REQ_WSH_META_DATA as FAIL_SEND_REQ_WSH_META_DATA, FAIL_SEND_SERVER_LOG_LEVEL as FAIL_SEND_SERVER_LOG_LEVEL, FAIL_SEND_STARTAPI as FAIL_SEND_STARTAPI, FAIL_SEND_SUBSCRIBETOGROUPEVENTS as FAIL_SEND_SUBSCRIBETOGROUPEVENTS, FAIL_SEND_UNSUBSCRIBEFROMGROUPEVENTS as FAIL_SEND_UNSUBSCRIBEFROMGROUPEVENTS, FAIL_SEND_UPDATEDISPLAYGROUP as FAIL_SEND_UPDATEDISPLAYGROUP, FAIL_SEND_VERIFYANDAUTHMESSAGE as FAIL_SEND_VERIFYANDAUTHMESSAGE, FAIL_SEND_VERIFYANDAUTHREQUEST as FAIL_SEND_VERIFYANDAUTHREQUEST, FAIL_SEND_VERIFYMESSAGE as FAIL_SEND_VERIFYMESSAGE, FAIL_SEND_VERIFYREQUEST as FAIL_SEND_VERIFYREQUEST, FA_PROFILE_NOT_SUPPORTED as FA_PROFILE_NOT_SUPPORTED, INVALID_SYMBOL as INVALID_SYMBOL, NOT_CONNECTED as NOT_CONNECTED, UPDATE_TWS as UPDATE_TWS
from ibapi.execution import ExecutionFilter as ExecutionFilter
from ibapi.message import OUT as OUT
from ibapi.order import COMPETE_AGAINST_BEST_OFFSET_UP_TO_MID as COMPETE_AGAINST_BEST_OFFSET_UP_TO_MID, Order as Order
from ibapi.order_cancel import OrderCancel as OrderCancel
from ibapi.protobuf.AccountDataRequest_pb2 import AccountDataRequest as AccountDataRequestProto
from ibapi.protobuf.AccountSummaryRequest_pb2 import AccountSummaryRequest as AccountSummaryRequestProto
from ibapi.protobuf.AccountUpdatesMultiRequest_pb2 import AccountUpdatesMultiRequest as AccountUpdatesMultiRequestProto
from ibapi.protobuf.AllOpenOrdersRequest_pb2 import AllOpenOrdersRequest as AllOpenOrdersRequestProto
from ibapi.protobuf.AutoOpenOrdersRequest_pb2 import AutoOpenOrdersRequest as AutoOpenOrdersRequestProto
from ibapi.protobuf.CalculateImpliedVolatilityRequest_pb2 import CalculateImpliedVolatilityRequest as CalculateImpliedVolatilityRequestProto
from ibapi.protobuf.CalculateOptionPriceRequest_pb2 import CalculateOptionPriceRequest as CalculateOptionPriceRequestProto
from ibapi.protobuf.CancelAccountSummary_pb2 import CancelAccountSummary as CancelAccountSummaryProto
from ibapi.protobuf.CancelAccountUpdatesMulti_pb2 import CancelAccountUpdatesMulti as CancelAccountUpdatesMultiProto
from ibapi.protobuf.CancelCalculateImpliedVolatility_pb2 import CancelCalculateImpliedVolatility as CancelCalculateImpliedVolatilityProto
from ibapi.protobuf.CancelCalculateOptionPrice_pb2 import CancelCalculateOptionPrice as CancelCalculateOptionPriceProto
from ibapi.protobuf.CancelFundamentalsData_pb2 import CancelFundamentalsData as CancelFundamentalsDataProto
from ibapi.protobuf.CancelHeadTimestamp_pb2 import CancelHeadTimestamp as CancelHeadTimestampProto
from ibapi.protobuf.CancelHistogramData_pb2 import CancelHistogramData as CancelHistogramDataProto
from ibapi.protobuf.CancelHistoricalData_pb2 import CancelHistoricalData as CancelHistoricalDataProto
from ibapi.protobuf.CancelMarketData_pb2 import CancelMarketData as CancelMarketDataProto
from ibapi.protobuf.CancelMarketDepth_pb2 import CancelMarketDepth as CancelMarketDepthProto
from ibapi.protobuf.CancelNewsBulletins_pb2 import CancelNewsBulletins as CancelNewsBulletinsProto
from ibapi.protobuf.CancelOrderRequest_pb2 import CancelOrderRequest as CancelOrderRequestProto
from ibapi.protobuf.CancelPnLSingle_pb2 import CancelPnLSingle as CancelPnLSingleProto
from ibapi.protobuf.CancelPnL_pb2 import CancelPnL as CancelPnLProto
from ibapi.protobuf.CancelPositionsMulti_pb2 import CancelPositionsMulti as CancelPositionsMultiProto
from ibapi.protobuf.CancelPositions_pb2 import CancelPositions as CancelPositionsProto
from ibapi.protobuf.CancelRealTimeBars_pb2 import CancelRealTimeBars as CancelRealTimeBarsProto
from ibapi.protobuf.CancelScannerSubscription_pb2 import CancelScannerSubscription as CancelScannerSubscriptionProto
from ibapi.protobuf.CancelTickByTick_pb2 import CancelTickByTick as CancelTickByTickProto
from ibapi.protobuf.CancelWshEventData_pb2 import CancelWshEventData as CancelWshEventDataProto
from ibapi.protobuf.CancelWshMetaData_pb2 import CancelWshMetaData as CancelWshMetaDataProto
from ibapi.protobuf.CompletedOrdersRequest_pb2 import CompletedOrdersRequest as CompletedOrdersRequestProto
from ibapi.protobuf.ContractDataRequest_pb2 import ContractDataRequest as ContractDataRequestProto
from ibapi.protobuf.CurrentTimeInMillisRequest_pb2 import CurrentTimeInMillisRequest as CurrentTimeInMillisRequestProto
from ibapi.protobuf.CurrentTimeRequest_pb2 import CurrentTimeRequest as CurrentTimeRequestProto
from ibapi.protobuf.ExecutionRequest_pb2 import ExecutionRequest as ExecutionRequestProto
from ibapi.protobuf.ExerciseOptionsRequest_pb2 import ExerciseOptionsRequest as ExerciseOptionsRequestProto
from ibapi.protobuf.FAReplace_pb2 import FAReplace as FAReplaceProto
from ibapi.protobuf.FARequest_pb2 import FARequest as FARequestProto
from ibapi.protobuf.FamilyCodesRequest_pb2 import FamilyCodesRequest as FamilyCodesRequestProto
from ibapi.protobuf.FundamentalsDataRequest_pb2 import FundamentalsDataRequest as FundamentalsDataRequestProto
from ibapi.protobuf.GlobalCancelRequest_pb2 import GlobalCancelRequest as GlobalCancelRequestProto
from ibapi.protobuf.HeadTimestampRequest_pb2 import HeadTimestampRequest as HeadTimestampRequestProto
from ibapi.protobuf.HistogramDataRequest_pb2 import HistogramDataRequest as HistogramDataRequestProto
from ibapi.protobuf.HistoricalDataRequest_pb2 import HistoricalDataRequest as HistoricalDataRequestProto
from ibapi.protobuf.HistoricalNewsRequest_pb2 import HistoricalNewsRequest as HistoricalNewsRequestProto
from ibapi.protobuf.HistoricalTicksRequest_pb2 import HistoricalTicksRequest as HistoricalTicksRequestProto
from ibapi.protobuf.IdsRequest_pb2 import IdsRequest as IdsRequestProto
from ibapi.protobuf.ManagedAccountsRequest_pb2 import ManagedAccountsRequest as ManagedAccountsRequestProto
from ibapi.protobuf.MarketDataRequest_pb2 import MarketDataRequest as MarketDataRequestProto
from ibapi.protobuf.MarketDataTypeRequest_pb2 import MarketDataTypeRequest as MarketDataTypeRequestProto
from ibapi.protobuf.MarketDepthExchangesRequest_pb2 import MarketDepthExchangesRequest as MarketDepthExchangesRequestProto
from ibapi.protobuf.MarketDepthRequest_pb2 import MarketDepthRequest as MarketDepthRequestProto
from ibapi.protobuf.MarketRuleRequest_pb2 import MarketRuleRequest as MarketRuleRequestProto
from ibapi.protobuf.MatchingSymbolsRequest_pb2 import MatchingSymbolsRequest as MatchingSymbolsRequestProto
from ibapi.protobuf.NewsArticleRequest_pb2 import NewsArticleRequest as NewsArticleRequestProto
from ibapi.protobuf.NewsBulletinsRequest_pb2 import NewsBulletinsRequest as NewsBulletinsRequestProto
from ibapi.protobuf.NewsProvidersRequest_pb2 import NewsProvidersRequest as NewsProvidersRequestProto
from ibapi.protobuf.OpenOrdersRequest_pb2 import OpenOrdersRequest as OpenOrdersRequestProto
from ibapi.protobuf.PlaceOrderRequest_pb2 import PlaceOrderRequest as PlaceOrderRequestProto
from ibapi.protobuf.PnLRequest_pb2 import PnLRequest as PnLRequestProto
from ibapi.protobuf.PnLSingleRequest_pb2 import PnLSingleRequest as PnLSingleRequestProto
from ibapi.protobuf.PositionsMultiRequest_pb2 import PositionsMultiRequest as PositionsMultiRequestProto
from ibapi.protobuf.PositionsRequest_pb2 import PositionsRequest as PositionsRequestProto
from ibapi.protobuf.QueryDisplayGroupsRequest_pb2 import QueryDisplayGroupsRequest as QueryDisplayGroupsRequestProto
from ibapi.protobuf.RealTimeBarsRequest_pb2 import RealTimeBarsRequest as RealTimeBarsRequestProto
from ibapi.protobuf.ScannerParametersRequest_pb2 import ScannerParametersRequest as ScannerParametersRequestProto
from ibapi.protobuf.ScannerSubscriptionRequest_pb2 import ScannerSubscriptionRequest as ScannerSubscriptionRequestProto
from ibapi.protobuf.SecDefOptParamsRequest_pb2 import SecDefOptParamsRequest as SecDefOptParamsRequestProto
from ibapi.protobuf.SetServerLogLevelRequest_pb2 import SetServerLogLevelRequest as SetServerLogLevelRequestProto
from ibapi.protobuf.SmartComponentsRequest_pb2 import SmartComponentsRequest as SmartComponentsRequestProto
from ibapi.protobuf.SoftDollarTiersRequest_pb2 import SoftDollarTiersRequest as SoftDollarTiersRequestProto
from ibapi.protobuf.StartApiRequest_pb2 import StartApiRequest as StartApiRequestProto
from ibapi.protobuf.SubscribeToGroupEventsRequest_pb2 import SubscribeToGroupEventsRequest as SubscribeToGroupEventsRequestProto
from ibapi.protobuf.TickByTickRequest_pb2 import TickByTickRequest as TickByTickRequestProto
from ibapi.protobuf.UnsubscribeFromGroupEventsRequest_pb2 import UnsubscribeFromGroupEventsRequest as UnsubscribeFromGroupEventsRequestProto
from ibapi.protobuf.UpdateDisplayGroupRequest_pb2 import UpdateDisplayGroupRequest as UpdateDisplayGroupRequestProto
from ibapi.protobuf.UserInfoRequest_pb2 import UserInfoRequest as UserInfoRequestProto
from ibapi.protobuf.VerifyMessageRequest_pb2 import VerifyMessageRequest as VerifyMessageRequestProto
from ibapi.protobuf.VerifyRequest_pb2 import VerifyRequest as VerifyRequestProto
from ibapi.protobuf.WshEventDataRequest_pb2 import WshEventDataRequest as WshEventDataRequestProto
from ibapi.protobuf.WshMetaDataRequest_pb2 import WshMetaDataRequest as WshMetaDataRequestProto
from ibapi.scanner import ScannerSubscription as ScannerSubscription
from ibapi.server_versions import MAX_CLIENT_VER as MAX_CLIENT_VER, MIN_CLIENT_VER as MIN_CLIENT_VER, MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_1 as MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_1, MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_2 as MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_2, MIN_SERVER_VER_ADVANCED_ORDER_REJECT as MIN_SERVER_VER_ADVANCED_ORDER_REJECT, MIN_SERVER_VER_ALGO_ID as MIN_SERVER_VER_ALGO_ID, MIN_SERVER_VER_ALGO_ORDERS as MIN_SERVER_VER_ALGO_ORDERS, MIN_SERVER_VER_AUTO_CANCEL_PARENT as MIN_SERVER_VER_AUTO_CANCEL_PARENT, MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE as MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE, MIN_SERVER_VER_BOND_ISSUERID as MIN_SERVER_VER_BOND_ISSUERID, MIN_SERVER_VER_CANCEL_CONTRACT_DATA as MIN_SERVER_VER_CANCEL_CONTRACT_DATA, MIN_SERVER_VER_CANCEL_HEADTIMESTAMP as MIN_SERVER_VER_CANCEL_HEADTIMESTAMP, MIN_SERVER_VER_CASH_QTY as MIN_SERVER_VER_CASH_QTY, MIN_SERVER_VER_CME_TAGGING_FIELDS as MIN_SERVER_VER_CME_TAGGING_FIELDS, MIN_SERVER_VER_CONTRACT_DATA_CHAIN as MIN_SERVER_VER_CONTRACT_DATA_CHAIN, MIN_SERVER_VER_CURRENT_TIME_IN_MILLIS as MIN_SERVER_VER_CURRENT_TIME_IN_MILLIS, MIN_SERVER_VER_CUSTOMER_ACCOUNT as MIN_SERVER_VER_CUSTOMER_ACCOUNT, MIN_SERVER_VER_DECISION_MAKER as MIN_SERVER_VER_DECISION_MAKER, MIN_SERVER_VER_DELTA_NEUTRAL as MIN_SERVER_VER_DELTA_NEUTRAL, MIN_SERVER_VER_DELTA_NEUTRAL_CONID as MIN_SERVER_VER_DELTA_NEUTRAL_CONID, MIN_SERVER_VER_DELTA_NEUTRAL_OPEN_CLOSE as MIN_SERVER_VER_DELTA_NEUTRAL_OPEN_CLOSE, MIN_SERVER_VER_DURATION as MIN_SERVER_VER_DURATION, MIN_SERVER_VER_D_PEG_ORDERS as MIN_SERVER_VER_D_PEG_ORDERS, MIN_SERVER_VER_EXECUTION_DATA_CHAIN as MIN_SERVER_VER_EXECUTION_DATA_CHAIN, MIN_SERVER_VER_EXT_OPERATOR as MIN_SERVER_VER_EXT_OPERATOR, MIN_SERVER_VER_FA_PROFILE_DESUPPORT as MIN_SERVER_VER_FA_PROFILE_DESUPPORT, MIN_SERVER_VER_FRACTIONAL_POSITIONS as MIN_SERVER_VER_FRACTIONAL_POSITIONS, MIN_SERVER_VER_FUNDAMENTAL_DATA as MIN_SERVER_VER_FUNDAMENTAL_DATA, MIN_SERVER_VER_HEDGE_ORDERS as MIN_SERVER_VER_HEDGE_ORDERS, MIN_SERVER_VER_HISTORICAL_SCHEDULE as MIN_SERVER_VER_HISTORICAL_SCHEDULE, MIN_SERVER_VER_HISTORICAL_TICKS as MIN_SERVER_VER_HISTORICAL_TICKS, MIN_SERVER_VER_IMBALANCE_ONLY as MIN_SERVER_VER_IMBALANCE_ONLY, MIN_SERVER_VER_INCLUDE_OVERNIGHT as MIN_SERVER_VER_INCLUDE_OVERNIGHT, MIN_SERVER_VER_LINKING as MIN_SERVER_VER_LINKING, MIN_SERVER_VER_MANUAL_ORDER_TIME as MIN_SERVER_VER_MANUAL_ORDER_TIME, MIN_SERVER_VER_MANUAL_ORDER_TIME_EXERCISE_OPTIONS as MIN_SERVER_VER_MANUAL_ORDER_TIME_EXERCISE_OPTIONS, MIN_SERVER_VER_MARKET_RULES as MIN_SERVER_VER_MARKET_RULES, MIN_SERVER_VER_MIFID_EXECUTION as MIN_SERVER_VER_MIFID_EXECUTION, MIN_SERVER_VER_MKT_DEPTH_PRIM_EXCHANGE as MIN_SERVER_VER_MKT_DEPTH_PRIM_EXCHANGE, MIN_SERVER_VER_MODELS_SUPPORT as MIN_SERVER_VER_MODELS_SUPPORT, MIN_SERVER_VER_NEWS_QUERY_ORIGINS as MIN_SERVER_VER_NEWS_QUERY_ORIGINS, MIN_SERVER_VER_NOT_HELD as MIN_SERVER_VER_NOT_HELD, MIN_SERVER_VER_OPTIONAL_CAPABILITIES as MIN_SERVER_VER_OPTIONAL_CAPABILITIES, MIN_SERVER_VER_OPT_OUT_SMART_ROUTING as MIN_SERVER_VER_OPT_OUT_SMART_ROUTING, MIN_SERVER_VER_ORDER_COMBO_LEGS_PRICE as MIN_SERVER_VER_ORDER_COMBO_LEGS_PRICE, MIN_SERVER_VER_ORDER_CONTAINER as MIN_SERVER_VER_ORDER_CONTAINER, MIN_SERVER_VER_ORDER_SOLICITED as MIN_SERVER_VER_ORDER_SOLICITED, MIN_SERVER_VER_PARAMETRIZED_DAYS_OF_EXECUTIONS as MIN_SERVER_VER_PARAMETRIZED_DAYS_OF_EXECUTIONS, MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS as MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS, MIN_SERVER_VER_PEGGED_TO_BENCHMARK as MIN_SERVER_VER_PEGGED_TO_BENCHMARK, MIN_SERVER_VER_PLACE_ORDER_CONID as MIN_SERVER_VER_PLACE_ORDER_CONID, MIN_SERVER_VER_PNL as MIN_SERVER_VER_PNL, MIN_SERVER_VER_POSITIONS as MIN_SERVER_VER_POSITIONS, MIN_SERVER_VER_POST_TO_ATS as MIN_SERVER_VER_POST_TO_ATS, MIN_SERVER_VER_PRICE_MGMT_ALGO as MIN_SERVER_VER_PRICE_MGMT_ALGO, MIN_SERVER_VER_PRIMARYEXCH as MIN_SERVER_VER_PRIMARYEXCH, MIN_SERVER_VER_PROFESSIONAL_CUSTOMER as MIN_SERVER_VER_PROFESSIONAL_CUSTOMER, MIN_SERVER_VER_PROTOBUF as MIN_SERVER_VER_PROTOBUF, MIN_SERVER_VER_PTA_ORDERS as MIN_SERVER_VER_PTA_ORDERS, MIN_SERVER_VER_RANDOMIZE_SIZE_AND_PRICE as MIN_SERVER_VER_RANDOMIZE_SIZE_AND_PRICE, MIN_SERVER_VER_REPLACE_FA_END as MIN_SERVER_VER_REPLACE_FA_END, MIN_SERVER_VER_REQ_CALC_IMPLIED_VOLAT as MIN_SERVER_VER_REQ_CALC_IMPLIED_VOLAT, MIN_SERVER_VER_REQ_FAMILY_CODES as MIN_SERVER_VER_REQ_FAMILY_CODES, MIN_SERVER_VER_REQ_HEAD_TIMESTAMP as MIN_SERVER_VER_REQ_HEAD_TIMESTAMP, MIN_SERVER_VER_REQ_HISTOGRAM as MIN_SERVER_VER_REQ_HISTOGRAM, MIN_SERVER_VER_REQ_HISTORICAL_NEWS as MIN_SERVER_VER_REQ_HISTORICAL_NEWS, MIN_SERVER_VER_REQ_MARKET_DATA_TYPE as MIN_SERVER_VER_REQ_MARKET_DATA_TYPE, MIN_SERVER_VER_REQ_MATCHING_SYMBOLS as MIN_SERVER_VER_REQ_MATCHING_SYMBOLS, MIN_SERVER_VER_REQ_MKT_DATA_CONID as MIN_SERVER_VER_REQ_MKT_DATA_CONID, MIN_SERVER_VER_REQ_MKT_DEPTH_EXCHANGES as MIN_SERVER_VER_REQ_MKT_DEPTH_EXCHANGES, MIN_SERVER_VER_REQ_NEWS_ARTICLE as MIN_SERVER_VER_REQ_NEWS_ARTICLE, MIN_SERVER_VER_REQ_NEWS_PROVIDERS as MIN_SERVER_VER_REQ_NEWS_PROVIDERS, MIN_SERVER_VER_REQ_SMART_COMPONENTS as MIN_SERVER_VER_REQ_SMART_COMPONENTS, MIN_SERVER_VER_RFQ_FIELDS as MIN_SERVER_VER_RFQ_FIELDS, MIN_SERVER_VER_SCALE_ORDERS2 as MIN_SERVER_VER_SCALE_ORDERS2, MIN_SERVER_VER_SCALE_ORDERS3 as MIN_SERVER_VER_SCALE_ORDERS3, MIN_SERVER_VER_SCALE_TABLE as MIN_SERVER_VER_SCALE_TABLE, MIN_SERVER_VER_SCANNER_GENERIC_OPTS as MIN_SERVER_VER_SCANNER_GENERIC_OPTS, MIN_SERVER_VER_SEC_DEF_OPT_PARAMS_REQ as MIN_SERVER_VER_SEC_DEF_OPT_PARAMS_REQ, MIN_SERVER_VER_SEC_ID_TYPE as MIN_SERVER_VER_SEC_ID_TYPE, MIN_SERVER_VER_SMART_COMBO_ROUTING_PARAMS as MIN_SERVER_VER_SMART_COMBO_ROUTING_PARAMS, MIN_SERVER_VER_SMART_DEPTH as MIN_SERVER_VER_SMART_DEPTH, MIN_SERVER_VER_SOFT_DOLLAR_TIER as MIN_SERVER_VER_SOFT_DOLLAR_TIER, MIN_SERVER_VER_SSHORTX as MIN_SERVER_VER_SSHORTX, MIN_SERVER_VER_SSHORTX_OLD as MIN_SERVER_VER_SSHORTX_OLD, MIN_SERVER_VER_SYNT_REALTIME_BARS as MIN_SERVER_VER_SYNT_REALTIME_BARS, MIN_SERVER_VER_TICK_BY_TICK as MIN_SERVER_VER_TICK_BY_TICK, MIN_SERVER_VER_TICK_BY_TICK_IGNORE_SIZE as MIN_SERVER_VER_TICK_BY_TICK_IGNORE_SIZE, MIN_SERVER_VER_TRADING_CLASS as MIN_SERVER_VER_TRADING_CLASS, MIN_SERVER_VER_TRAILING_PERCENT as MIN_SERVER_VER_TRAILING_PERCENT, MIN_SERVER_VER_UNDO_RFQ_FIELDS as MIN_SERVER_VER_UNDO_RFQ_FIELDS, MIN_SERVER_VER_USER_INFO as MIN_SERVER_VER_USER_INFO, MIN_SERVER_VER_WSHE_CALENDAR as MIN_SERVER_VER_WSHE_CALENDAR, MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS as MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS, MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS_DATE as MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS_DATE
from ibapi.utils import BadMessage as BadMessage, ClientException as ClientException, currentTimeMillis as currentTimeMillis, current_fn_name as current_fn_name, isAsciiPrintable as isAsciiPrintable, isPegBenchOrder as isPegBenchOrder, isPegBestOrder as isPegBestOrder, isPegMidOrder as isPegMidOrder, log_ as log_

logger: Incomplete

class EClient:
    DISCONNECTED: Incomplete
    CONNECTING: Incomplete
    CONNECTED: Incomplete
    msg_queue: Incomplete
    wrapper: Incomplete
    decoder: Incomplete
    nKeybIntHard: int
    conn: Incomplete
    host: Incomplete
    port: Incomplete
    extraAuth: bool
    clientId: Incomplete
    serverVersion_: Incomplete
    connTime: Incomplete
    connState: Incomplete
    optCapab: Incomplete
    asynchronous: bool
    reader: Incomplete
    decode: Incomplete
    connectOptions: Incomplete
    def __init__(self, wrapper) -> None: ...
    def reset(self) -> None: ...
    def setConnState(self, connState) -> None: ...
    def sendMsgProtoBuf(self, msgId: int, msg: bytes): ...
    def sendMsg(self, msgId: int, msg: str): ...
    def logRequest(self, fnName, fnParams) -> None: ...
    def validateInvalidSymbols(self, host) -> None: ...
    def checkConnected(self) -> None: ...
    def useProtoBuf(self, msgId: int) -> bool: ...
    def startApi(self) -> None: ...
    def startApiProtoBuf(self, startApiRequestProto: StartApiRequestProto): ...
    def connect(self, host, port, clientId) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self): ...
    def keyboardInterrupt(self) -> None: ...
    def keyboardInterruptHard(self) -> None: ...
    def setConnectOptions(self, opts) -> None: ...
    def setOptionalCapabilities(self, optCapab) -> None: ...
    def msgLoopTmo(self) -> None: ...
    def msgLoopRec(self) -> None: ...
    def run(self) -> None: ...
    def reqCurrentTime(self) -> None: ...
    def reqCurrentTimeProtoBuf(self, currentTimeRequestProto: CurrentTimeRequestProto): ...
    def serverVersion(self): ...
    def setServerLogLevel(self, logLevel: int): ...
    def setServerLogLevelProtoBuf(self, setServerLogLevelRequestProto: SetServerLogLevelRequestProto): ...
    def twsConnectionTime(self): ...
    def reqMktData(self, reqId: TickerId, contract: Contract, genericTickList: str, snapshot: bool, regulatorySnapshot: bool, mktDataOptions: TagValueList): ...
    def reqMarketDataProtoBuf(self, marketDataRequestProto: MarketDataRequestProto): ...
    def cancelMktData(self, reqId: TickerId): ...
    def cancelMarketDataProtoBuf(self, cancelMarketDataProto: CancelMarketDataProto): ...
    def reqMarketDataType(self, marketDataType: int): ...
    def reqMarketDataTypeProtoBuf(self, marketDataTypeRequestProto: MarketDataTypeRequestProto): ...
    def reqSmartComponents(self, reqId: int, bboExchange: str): ...
    def reqSmartComponentsProtoBuf(self, smartComponentsRequestProto: SmartComponentsRequestProto): ...
    def reqMarketRule(self, marketRuleId: int): ...
    def reqMarketRuleProtoBuf(self, marketRuleRequestProto: MarketRuleRequestProto): ...
    def reqTickByTickData(self, reqId: int, contract: Contract, tickType: str, numberOfTicks: int, ignoreSize: bool): ...
    def reqTickByTickDataProtoBuf(self, tickByTickRequestProto: TickByTickRequestProto): ...
    def cancelTickByTickData(self, reqId: int): ...
    def cancelTickByTickProtoBuf(self, cancelTickByTickProto: CancelTickByTickProto): ...
    def calculateImpliedVolatility(self, reqId: TickerId, contract: Contract, optionPrice: float, underPrice: float, implVolOptions: TagValueList): ...
    def calculateImpliedVolatilityProtoBuf(self, calculateImpliedVolatilityRequestProto: CalculateImpliedVolatilityRequestProto): ...
    def cancelCalculateImpliedVolatility(self, reqId: TickerId): ...
    def cancelCalculateImpliedVolatilityProtoBuf(self, cancelCalculateImpliedVolatilityProto: CancelCalculateImpliedVolatilityProto): ...
    def calculateOptionPrice(self, reqId: TickerId, contract: Contract, volatility: float, underPrice: float, optPrcOptions: TagValueList): ...
    def calculateOptionPriceProtoBuf(self, calculateOptionPriceRequestProto: CalculateOptionPriceRequestProto): ...
    def cancelCalculateOptionPrice(self, reqId: TickerId): ...
    def cancelCalculateOptionPriceProtoBuf(self, cancelCalculateOptionPriceProto: CancelCalculateOptionPriceProto): ...
    def exerciseOptions(self, reqId: TickerId, contract: Contract, exerciseAction: int, exerciseQuantity: int, account: str, override: int, manualOrderTime: str, customerAccount: str, professionalCustomer: bool): ...
    def exerciseOptionsProtoBuf(self, exerciseOptionsRequestProto: ExerciseOptionsRequestProto): ...
    def placeOrder(self, orderId: OrderId, contract: Contract, order: Order): ...
    def placeOrderProtoBuf(self, placeOrderRequestProto: PlaceOrderRequestProto): ...
    def validateOrderParameters(self, order) -> str | None: ...
    def cancelOrder(self, orderId: OrderId, orderCancel: OrderCancel): ...
    def cancelOrderProtoBuf(self, cancelOrderRequestProto: CancelOrderRequestProto): ...
    def reqOpenOrders(self) -> None: ...
    def reqOpenOrdersProtoBuf(self, openOrdersRequestProto: OpenOrdersRequestProto): ...
    def reqAutoOpenOrders(self, bAutoBind: bool): ...
    def reqAutoOpenOrdersProtoBuf(self, autoOpenOrdersRequestProto: AutoOpenOrdersRequestProto): ...
    def reqAllOpenOrders(self) -> None: ...
    def reqAllOpenOrdersProtoBuf(self, allOpenOrdersRequestProto: AllOpenOrdersRequestProto): ...
    def reqGlobalCancel(self, orderCancel: OrderCancel): ...
    def reqGlobalCancelProtoBuf(self, globalCancelRequestProto: GlobalCancelRequestProto): ...
    def reqIds(self, numIds: int): ...
    def reqIdsProtoBuf(self, idsRequestProto: IdsRequestProto): ...
    def reqAccountUpdates(self, subscribe: bool, acctCode: str): ...
    def reqAccountUpdatesProtoBuf(self, accountDataRequestProto: AccountDataRequestProto): ...
    def reqAccountSummary(self, reqId: int, groupName: str, tags: str): ...
    def reqAccountSummaryProtoBuf(self, accountSummaryRequestProto: AccountSummaryRequestProto): ...
    def cancelAccountSummary(self, reqId: int): ...
    def cancelAccountSummaryProtoBuf(self, cancelAccountSummaryProto: CancelAccountSummaryProto): ...
    def reqPositions(self) -> None: ...
    def reqPositionsProtoBuf(self, positionsRequestProto: PositionsRequestProto): ...
    def cancelPositions(self) -> None: ...
    def cancelPositionsProtoBuf(self, cancelPositionsProto: CancelPositionsProto): ...
    def reqPositionsMulti(self, reqId: int, account: str, modelCode: str): ...
    def reqPositionsMultiProtoBuf(self, positionsMultiRequestProto: PositionsMultiRequestProto): ...
    def cancelPositionsMulti(self, reqId: int): ...
    def cancelPositionsMultiProtoBuf(self, cancelPositionsMultiProto: CancelPositionsMultiProto): ...
    def reqAccountUpdatesMulti(self, reqId: int, account: str, modelCode: str, ledgerAndNLV: bool): ...
    def reqAccountUpdatesMultiProtoBuf(self, accountUpdatesMultiRequestProto: AccountUpdatesMultiRequestProto): ...
    def cancelAccountUpdatesMulti(self, reqId: int): ...
    def cancelAccountUpdatesMultiProtoBuf(self, cancelAccountUpdatesMultiProto: CancelAccountUpdatesMultiProto): ...
    def reqPnL(self, reqId: int, account: str, modelCode: str): ...
    def reqPnLProtoBuf(self, pnlRequestProto: PnLRequestProto): ...
    def cancelPnL(self, reqId: int): ...
    def cancelPnLProtoBuf(self, cancelPnLProto: CancelPnLProto): ...
    def reqPnLSingle(self, reqId: int, account: str, modelCode: str, conid: int): ...
    def reqPnLSingleProtoBuf(self, pnlSingleRequestProto: PnLSingleRequestProto): ...
    def cancelPnLSingle(self, reqId: int): ...
    def cancelPnLSingleProtoBuf(self, cancelPnLSingleProto: CancelPnLSingleProto): ...
    def reqExecutions(self, reqId: int, execFilter: ExecutionFilter): ...
    def reqExecutionsProtoBuf(self, executionRequestProto: ExecutionRequestProto): ...
    def reqContractDetails(self, reqId: int, contract: Contract): ...
    def reqContractDataProtoBuf(self, contractDataRequestProto: ContractDataRequestProto): ...
    def reqMktDepthExchanges(self) -> None: ...
    def reqMarketDepthExchangesProtoBuf(self, marketDepthExchangesRequestProto: MarketDepthExchangesRequestProto): ...
    def reqMktDepth(self, reqId: TickerId, contract: Contract, numRows: int, isSmartDepth: bool, mktDepthOptions: TagValueList): ...
    def reqMarketDepthProtoBuf(self, marketDepthRequestProto: MarketDepthRequestProto): ...
    def cancelMktDepth(self, reqId: TickerId, isSmartDepth: bool): ...
    def cancelMarketDepthProtoBuf(self, cancelMarketDepthProto: CancelMarketDepthProto): ...
    def reqNewsBulletins(self, allMsgs: bool): ...
    def reqNewsBulletinsProtoBuf(self, newsBulletinsRequestProto: NewsBulletinsRequestProto): ...
    def cancelNewsBulletins(self) -> None: ...
    def cancelNewsBulletinsProtoBuf(self, cancelNewsBulletinsProto: CancelNewsBulletinsProto): ...
    def reqManagedAccts(self): ...
    def reqManagedAcctsProtoBuf(self, managedAccountsRequestProto: ManagedAccountsRequestProto): ...
    def requestFA(self, faData: FaDataType): ...
    def reqFAProtoBuf(self, faRequestProto: FARequestProto): ...
    def replaceFA(self, reqId: TickerId, faData: FaDataType, cxml: str): ...
    def replaceFAProtoBuf(self, faReplaceProto: FAReplaceProto): ...
    def reqHistoricalData(self, reqId: TickerId, contract: Contract, endDateTime: str, durationStr: str, barSizeSetting: str, whatToShow: str, useRTH: int, formatDate: int, keepUpToDate: bool, chartOptions: TagValueList): ...
    def reqHistoricalDataProtoBuf(self, historicalDataRequestProto: HistoricalDataRequestProto): ...
    def cancelHistoricalData(self, reqId: TickerId): ...
    def cancelHistoricalDataProtoBuf(self, cancelHistoricalDataProto: CancelHistoricalDataProto): ...
    def reqHeadTimeStamp(self, reqId: TickerId, contract: Contract, whatToShow: str, useRTH: int, formatDate: int): ...
    def reqHeadTimestampProtoBuf(self, headTimestampRequestProto: HeadTimestampRequestProto): ...
    def cancelHeadTimeStamp(self, reqId: TickerId): ...
    def cancelHeadTimestampProtoBuf(self, cancelHeadTimestampProto: CancelHeadTimestampProto): ...
    def reqHistogramData(self, tickerId: int, contract: Contract, useRTH: bool, timePeriod: str): ...
    def reqHistogramDataProtoBuf(self, histogramDataRequestProto: HistogramDataRequestProto): ...
    def cancelHistogramData(self, tickerId: int): ...
    def cancelHistogramDataProtoBuf(self, cancelHistogramDataProto: CancelHistogramDataProto): ...
    def reqHistoricalTicks(self, reqId: int, contract: Contract, startDateTime: str, endDateTime: str, numberOfTicks: int, whatToShow: str, useRth: int, ignoreSize: bool, miscOptions: TagValueList): ...
    def reqHistoricalTicksProtoBuf(self, historicalTicksRequestProto: HistoricalTicksRequestProto): ...
    def reqScannerParameters(self) -> None: ...
    def reqScannerParametersProtoBuf(self, scannerParametersRequestProto: ScannerParametersRequestProto): ...
    def reqScannerSubscription(self, reqId: int, subscription: ScannerSubscription, scannerSubscriptionOptions: TagValueList, scannerSubscriptionFilterOptions: TagValueList): ...
    def reqScannerSubscriptionProtoBuf(self, scannerSubscriptionRequestProto: ScannerSubscriptionRequestProto): ...
    def cancelScannerSubscription(self, reqId: int): ...
    def cancelScannerSubscriptionProtoBuf(self, cancelScannerSubscriptionProto: CancelScannerSubscriptionProto): ...
    def reqRealTimeBars(self, reqId: TickerId, contract: Contract, barSize: int, whatToShow: str, useRTH: bool, realTimeBarsOptions: TagValueList): ...
    def reqRealTimeBarsProtoBuf(self, realTimeBarsRequestProto: RealTimeBarsRequestProto): ...
    def cancelRealTimeBars(self, reqId: TickerId): ...
    def cancelRealTimeBarsProtoBuf(self, cancelRealTimeBarsProto: CancelRealTimeBarsProto): ...
    def reqFundamentalData(self, reqId: TickerId, contract: Contract, reportType: str, fundamentalDataOptions: TagValueList): ...
    def reqFundamentalsDataProtoBuf(self, fundamentalsDataRequestProto: FundamentalsDataRequestProto): ...
    def cancelFundamentalData(self, reqId: TickerId): ...
    def cancelFundamentalsDataProtoBuf(self, cancelFundamentalsDataProto: CancelFundamentalsDataProto): ...
    def reqNewsProviders(self) -> None: ...
    def reqNewsProvidersProtoBuf(self, newsProvidersRequestProto: NewsProvidersRequestProto): ...
    def reqNewsArticle(self, reqId: int, providerCode: str, articleId: str, newsArticleOptions: TagValueList): ...
    def reqNewsArticleProtoBuf(self, newsArticleRequestProto: NewsArticleRequestProto): ...
    def reqHistoricalNews(self, reqId: int, conId: int, providerCodes: str, startDateTime: str, endDateTime: str, totalResults: int, historicalNewsOptions: TagValueList): ...
    def reqHistoricalNewsProtoBuf(self, historicalNewsRequestProto: HistoricalNewsRequestProto): ...
    def queryDisplayGroups(self, reqId: int): ...
    def queryDisplayGroupsProtoBuf(self, queryDisplayGroupsRequestProto: QueryDisplayGroupsRequestProto): ...
    def subscribeToGroupEvents(self, reqId: int, groupId: int): ...
    def subscribeToGroupEventsProtoBuf(self, subscribeToGroupEventsRequestProto: SubscribeToGroupEventsRequestProto): ...
    def updateDisplayGroup(self, reqId: int, contractInfo: str): ...
    def updateDisplayGroupProtoBuf(self, updateDisplayGroupRequestProto: UpdateDisplayGroupRequestProto): ...
    def unsubscribeFromGroupEvents(self, reqId: int): ...
    def unsubscribeFromGroupEventsProtoBuf(self, unsubscribeFromGroupEventsRequestProto: UnsubscribeFromGroupEventsRequestProto): ...
    def verifyRequest(self, apiName: str, apiVersion: str): ...
    def verifyRequestProtoBuf(self, verifyRequestProto: VerifyRequestProto): ...
    def verifyMessage(self, apiData: str): ...
    def verifyMessageProtoBuf(self, verifyMessageRequestProto: VerifyMessageRequestProto): ...
    def verifyAndAuthRequest(self, apiName: str, apiVersion: str, opaqueIsvKey: str): ...
    def verifyAndAuthMessage(self, apiData: str, xyzResponse: str): ...
    def reqSecDefOptParams(self, reqId: int, underlyingSymbol: str, futFopExchange: str, underlyingSecType: str, underlyingConId: int): ...
    def reqSecDefOptParamsProtoBuf(self, secDefOptParamsRequestProto: SecDefOptParamsRequestProto): ...
    def reqSoftDollarTiers(self, reqId: int): ...
    def reqSoftDollarTiersProtoBuf(self, softDollarTiersRequestProto: SoftDollarTiersRequestProto): ...
    def reqFamilyCodes(self) -> None: ...
    def reqFamilyCodesProtoBuf(self, familyCodesRequestProto: FamilyCodesRequestProto): ...
    def reqMatchingSymbols(self, reqId: int, pattern: str): ...
    def reqMatchingSymbolsProtoBuf(self, matchingSymbolsRequestProto: MatchingSymbolsRequestProto): ...
    def reqCompletedOrders(self, apiOnly: bool): ...
    def reqCompletedOrdersProtoBuf(self, completedOrdersRequestProto: CompletedOrdersRequestProto): ...
    def reqWshMetaData(self, reqId: int): ...
    def reqWshMetaDataProtoBuf(self, wshMetaDataRequestProto: WshMetaDataRequestProto): ...
    def cancelWshMetaData(self, reqId: int): ...
    def cancelWshMetaDataProtoBuf(self, cancelWshMetaDataProto: CancelWshMetaDataProto): ...
    def reqWshEventData(self, reqId: int, wshEventData: WshEventData): ...
    def reqWshEventDataProtoBuf(self, wshEventDataRequestProto: WshEventDataRequestProto): ...
    def cancelWshEventData(self, reqId: int): ...
    def cancelWshEventDataProtoBuf(self, cancelWshEventDataProto: CancelWshEventDataProto): ...
    def reqUserInfo(self, reqId: int): ...
    def reqUserInfoProtoBuf(self, userInfoRequestProto: UserInfoRequestProto): ...
    def reqCurrentTimeInMillis(self) -> None: ...
    def reqCurrentTimeInMillisProtoBuf(self, currentTimeInMillisRequestProto: CurrentTimeInMillisRequestProto): ...
    def cancelContractData(self, reqId: int): ...
    def cancelContractDataProtoBuf(self, cancelContractDataProto) -> None: ...
    def cancelHistoricalTicks(self, reqId: TickerId): ...
    def cancelHistoricalTicksProtoBuf(self, cancelHistoricalTicksProto) -> None: ...
