from ibapi.common import *
from _typeshed import Incomplete
from ibapi import comm as comm, decoder as decoder, reader as reader
from ibapi.comm import make_field as make_field, make_field_handle_empty as make_field_handle_empty
from ibapi.connection import Connection as Connection
from ibapi.const import MAX_MSG_LEN as MAX_MSG_LEN, NO_VALID_ID as NO_VALID_ID, UNSET_DOUBLE as UNSET_DOUBLE, UNSET_INTEGER as UNSET_INTEGER
from ibapi.contract import Contract as Contract
from ibapi.errors import BAD_LENGTH as BAD_LENGTH, BAD_MESSAGE as BAD_MESSAGE, CONNECT_FAIL as CONNECT_FAIL, FA_PROFILE_NOT_SUPPORTED as FA_PROFILE_NOT_SUPPORTED, NOT_CONNECTED as NOT_CONNECTED, UPDATE_TWS as UPDATE_TWS
from ibapi.execution import ExecutionFilter as ExecutionFilter
from ibapi.message import OUT as OUT
from ibapi.order import COMPETE_AGAINST_BEST_OFFSET_UP_TO_MID as COMPETE_AGAINST_BEST_OFFSET_UP_TO_MID, Order as Order
from ibapi.scanner import ScannerSubscription as ScannerSubscription
from ibapi.server_versions import MAX_CLIENT_VER as MAX_CLIENT_VER, MIN_CLIENT_VER as MIN_CLIENT_VER, MIN_SERVER_VER_ADVANCED_ORDER_REJECT as MIN_SERVER_VER_ADVANCED_ORDER_REJECT, MIN_SERVER_VER_ALGO_ID as MIN_SERVER_VER_ALGO_ID, MIN_SERVER_VER_ALGO_ORDERS as MIN_SERVER_VER_ALGO_ORDERS, MIN_SERVER_VER_AUTO_CANCEL_PARENT as MIN_SERVER_VER_AUTO_CANCEL_PARENT, MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE as MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE, MIN_SERVER_VER_BOND_ISSUERID as MIN_SERVER_VER_BOND_ISSUERID, MIN_SERVER_VER_CANCEL_HEADTIMESTAMP as MIN_SERVER_VER_CANCEL_HEADTIMESTAMP, MIN_SERVER_VER_CASH_QTY as MIN_SERVER_VER_CASH_QTY, MIN_SERVER_VER_CONTRACT_DATA_CHAIN as MIN_SERVER_VER_CONTRACT_DATA_CHAIN, MIN_SERVER_VER_DECISION_MAKER as MIN_SERVER_VER_DECISION_MAKER, MIN_SERVER_VER_DELTA_NEUTRAL as MIN_SERVER_VER_DELTA_NEUTRAL, MIN_SERVER_VER_DELTA_NEUTRAL_CONID as MIN_SERVER_VER_DELTA_NEUTRAL_CONID, MIN_SERVER_VER_DELTA_NEUTRAL_OPEN_CLOSE as MIN_SERVER_VER_DELTA_NEUTRAL_OPEN_CLOSE, MIN_SERVER_VER_DURATION as MIN_SERVER_VER_DURATION, MIN_SERVER_VER_D_PEG_ORDERS as MIN_SERVER_VER_D_PEG_ORDERS, MIN_SERVER_VER_EXECUTION_DATA_CHAIN as MIN_SERVER_VER_EXECUTION_DATA_CHAIN, MIN_SERVER_VER_EXT_OPERATOR as MIN_SERVER_VER_EXT_OPERATOR, MIN_SERVER_VER_FA_PROFILE_DESUPPORT as MIN_SERVER_VER_FA_PROFILE_DESUPPORT, MIN_SERVER_VER_FRACTIONAL_POSITIONS as MIN_SERVER_VER_FRACTIONAL_POSITIONS, MIN_SERVER_VER_FUNDAMENTAL_DATA as MIN_SERVER_VER_FUNDAMENTAL_DATA, MIN_SERVER_VER_HEDGE_ORDERS as MIN_SERVER_VER_HEDGE_ORDERS, MIN_SERVER_VER_HISTORICAL_SCHEDULE as MIN_SERVER_VER_HISTORICAL_SCHEDULE, MIN_SERVER_VER_HISTORICAL_TICKS as MIN_SERVER_VER_HISTORICAL_TICKS, MIN_SERVER_VER_LINKING as MIN_SERVER_VER_LINKING, MIN_SERVER_VER_MANUAL_ORDER_TIME as MIN_SERVER_VER_MANUAL_ORDER_TIME, MIN_SERVER_VER_MANUAL_ORDER_TIME_EXERCISE_OPTIONS as MIN_SERVER_VER_MANUAL_ORDER_TIME_EXERCISE_OPTIONS, MIN_SERVER_VER_MARKET_RULES as MIN_SERVER_VER_MARKET_RULES, MIN_SERVER_VER_MIFID_EXECUTION as MIN_SERVER_VER_MIFID_EXECUTION, MIN_SERVER_VER_MKT_DEPTH_PRIM_EXCHANGE as MIN_SERVER_VER_MKT_DEPTH_PRIM_EXCHANGE, MIN_SERVER_VER_MODELS_SUPPORT as MIN_SERVER_VER_MODELS_SUPPORT, MIN_SERVER_VER_NEWS_QUERY_ORIGINS as MIN_SERVER_VER_NEWS_QUERY_ORIGINS, MIN_SERVER_VER_NOT_HELD as MIN_SERVER_VER_NOT_HELD, MIN_SERVER_VER_OPTIONAL_CAPABILITIES as MIN_SERVER_VER_OPTIONAL_CAPABILITIES, MIN_SERVER_VER_OPT_OUT_SMART_ROUTING as MIN_SERVER_VER_OPT_OUT_SMART_ROUTING, MIN_SERVER_VER_ORDER_COMBO_LEGS_PRICE as MIN_SERVER_VER_ORDER_COMBO_LEGS_PRICE, MIN_SERVER_VER_ORDER_CONTAINER as MIN_SERVER_VER_ORDER_CONTAINER, MIN_SERVER_VER_ORDER_SOLICITED as MIN_SERVER_VER_ORDER_SOLICITED, MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS as MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS, MIN_SERVER_VER_PEGGED_TO_BENCHMARK as MIN_SERVER_VER_PEGGED_TO_BENCHMARK, MIN_SERVER_VER_PLACE_ORDER_CONID as MIN_SERVER_VER_PLACE_ORDER_CONID, MIN_SERVER_VER_PNL as MIN_SERVER_VER_PNL, MIN_SERVER_VER_POSITIONS as MIN_SERVER_VER_POSITIONS, MIN_SERVER_VER_POST_TO_ATS as MIN_SERVER_VER_POST_TO_ATS, MIN_SERVER_VER_PRICE_MGMT_ALGO as MIN_SERVER_VER_PRICE_MGMT_ALGO, MIN_SERVER_VER_PRIMARYEXCH as MIN_SERVER_VER_PRIMARYEXCH, MIN_SERVER_VER_PTA_ORDERS as MIN_SERVER_VER_PTA_ORDERS, MIN_SERVER_VER_RANDOMIZE_SIZE_AND_PRICE as MIN_SERVER_VER_RANDOMIZE_SIZE_AND_PRICE, MIN_SERVER_VER_REPLACE_FA_END as MIN_SERVER_VER_REPLACE_FA_END, MIN_SERVER_VER_REQ_CALC_IMPLIED_VOLAT as MIN_SERVER_VER_REQ_CALC_IMPLIED_VOLAT, MIN_SERVER_VER_REQ_FAMILY_CODES as MIN_SERVER_VER_REQ_FAMILY_CODES, MIN_SERVER_VER_REQ_HEAD_TIMESTAMP as MIN_SERVER_VER_REQ_HEAD_TIMESTAMP, MIN_SERVER_VER_REQ_HISTOGRAM as MIN_SERVER_VER_REQ_HISTOGRAM, MIN_SERVER_VER_REQ_HISTORICAL_NEWS as MIN_SERVER_VER_REQ_HISTORICAL_NEWS, MIN_SERVER_VER_REQ_MARKET_DATA_TYPE as MIN_SERVER_VER_REQ_MARKET_DATA_TYPE, MIN_SERVER_VER_REQ_MATCHING_SYMBOLS as MIN_SERVER_VER_REQ_MATCHING_SYMBOLS, MIN_SERVER_VER_REQ_MKT_DATA_CONID as MIN_SERVER_VER_REQ_MKT_DATA_CONID, MIN_SERVER_VER_REQ_MKT_DEPTH_EXCHANGES as MIN_SERVER_VER_REQ_MKT_DEPTH_EXCHANGES, MIN_SERVER_VER_REQ_NEWS_ARTICLE as MIN_SERVER_VER_REQ_NEWS_ARTICLE, MIN_SERVER_VER_REQ_NEWS_PROVIDERS as MIN_SERVER_VER_REQ_NEWS_PROVIDERS, MIN_SERVER_VER_REQ_SMART_COMPONENTS as MIN_SERVER_VER_REQ_SMART_COMPONENTS, MIN_SERVER_VER_SCALE_ORDERS2 as MIN_SERVER_VER_SCALE_ORDERS2, MIN_SERVER_VER_SCALE_ORDERS3 as MIN_SERVER_VER_SCALE_ORDERS3, MIN_SERVER_VER_SCALE_TABLE as MIN_SERVER_VER_SCALE_TABLE, MIN_SERVER_VER_SCANNER_GENERIC_OPTS as MIN_SERVER_VER_SCANNER_GENERIC_OPTS, MIN_SERVER_VER_SEC_DEF_OPT_PARAMS_REQ as MIN_SERVER_VER_SEC_DEF_OPT_PARAMS_REQ, MIN_SERVER_VER_SEC_ID_TYPE as MIN_SERVER_VER_SEC_ID_TYPE, MIN_SERVER_VER_SMART_COMBO_ROUTING_PARAMS as MIN_SERVER_VER_SMART_COMBO_ROUTING_PARAMS, MIN_SERVER_VER_SMART_DEPTH as MIN_SERVER_VER_SMART_DEPTH, MIN_SERVER_VER_SOFT_DOLLAR_TIER as MIN_SERVER_VER_SOFT_DOLLAR_TIER, MIN_SERVER_VER_SSHORTX as MIN_SERVER_VER_SSHORTX, MIN_SERVER_VER_SSHORTX_OLD as MIN_SERVER_VER_SSHORTX_OLD, MIN_SERVER_VER_SYNT_REALTIME_BARS as MIN_SERVER_VER_SYNT_REALTIME_BARS, MIN_SERVER_VER_TICK_BY_TICK as MIN_SERVER_VER_TICK_BY_TICK, MIN_SERVER_VER_TICK_BY_TICK_IGNORE_SIZE as MIN_SERVER_VER_TICK_BY_TICK_IGNORE_SIZE, MIN_SERVER_VER_TRADING_CLASS as MIN_SERVER_VER_TRADING_CLASS, MIN_SERVER_VER_TRAILING_PERCENT as MIN_SERVER_VER_TRAILING_PERCENT, MIN_SERVER_VER_USER_INFO as MIN_SERVER_VER_USER_INFO, MIN_SERVER_VER_WSHE_CALENDAR as MIN_SERVER_VER_WSHE_CALENDAR, MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS as MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS
from ibapi.utils import BadMessage as BadMessage, ClientException as ClientException, current_fn_name as current_fn_name, isPegBenchOrder as isPegBenchOrder, isPegBestOrder as isPegBestOrder, isPegMidOrder as isPegMidOrder, log_ as log_

logger: Incomplete

class EClient:
    DISCONNECTED: Incomplete
    CONNECTING: Incomplete
    CONNECTED: Incomplete
    REDIRECT: Incomplete
    msg_queue: Incomplete
    wrapper: Incomplete
    decoder: Incomplete
    nKeybIntHard: int
    conn: Incomplete
    host: Incomplete
    port: Incomplete
    extraAuth: bool
    clientId: Incomplete
    serverVersion_: Incomplete
    connTime: Incomplete
    connState: Incomplete
    optCapab: str
    asynchronous: bool
    reader: Incomplete
    decode: Incomplete
    connectionOptions: Incomplete
    def __init__(self, wrapper) -> None: ...
    def reset(self) -> None: ...
    def setConnState(self, connState) -> None: ...
    def sendMsg(self, msg) -> None: ...
    def logRequest(self, fnName, fnParams) -> None: ...
    def startApi(self) -> None: ...
    def connect(self, host, port, clientId) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self): ...
    def keyboardInterrupt(self) -> None: ...
    def keyboardInterruptHard(self) -> None: ...
    def setConnectionOptions(self, opts) -> None: ...
    def msgLoopTmo(self) -> None: ...
    def msgLoopRec(self) -> None: ...
    def run(self) -> None: ...
    def reqCurrentTime(self) -> None: ...
    def serverVersion(self): ...
    def setServerLogLevel(self, logLevel: int): ...
    def twsConnectionTime(self): ...
    def reqMktData(self, reqId: TickerId, contract: Contract, genericTickList: str, snapshot: bool, regulatorySnapshot: bool, mktDataOptions: TagValueList): ...
    def cancelMktData(self, reqId: TickerId): ...
    def reqMarketDataType(self, marketDataType: int): ...
    def reqSmartComponents(self, reqId: int, bboExchange: str): ...
    def reqMarketRule(self, marketRuleId: int): ...
    def reqTickByTickData(self, reqId: int, contract: Contract, tickType: str, numberOfTicks: int, ignoreSize: bool): ...
    def cancelTickByTickData(self, reqId: int): ...
    def calculateImpliedVolatility(self, reqId: TickerId, contract: Contract, optionPrice: float, underPrice: float, implVolOptions: TagValueList): ...
    def cancelCalculateImpliedVolatility(self, reqId: TickerId): ...
    def calculateOptionPrice(self, reqId: TickerId, contract: Contract, volatility: float, underPrice: float, optPrcOptions: TagValueList): ...
    def cancelCalculateOptionPrice(self, reqId: TickerId): ...
    def exerciseOptions(self, reqId: TickerId, contract: Contract, exerciseAction: int, exerciseQuantity: int, account: str, override: int, manualOrderTime: str): ...
    def placeOrder(self, orderId: OrderId, contract: Contract, order: Order): ...
    def cancelOrder(self, orderId: OrderId, manualCancelOrderTime: str): ...
    def reqOpenOrders(self) -> None: ...
    def reqAutoOpenOrders(self, bAutoBind: bool): ...
    def reqAllOpenOrders(self) -> None: ...
    def reqGlobalCancel(self) -> None: ...
    def reqIds(self, numIds: int): ...
    def reqAccountUpdates(self, subscribe: bool, acctCode: str): ...
    def reqAccountSummary(self, reqId: int, groupName: str, tags: str): ...
    def cancelAccountSummary(self, reqId: int): ...
    def reqPositions(self) -> None: ...
    def cancelPositions(self) -> None: ...
    def reqPositionsMulti(self, reqId: int, account: str, modelCode: str): ...
    def cancelPositionsMulti(self, reqId: int): ...
    def reqAccountUpdatesMulti(self, reqId: int, account: str, modelCode: str, ledgerAndNLV: bool): ...
    def cancelAccountUpdatesMulti(self, reqId: int): ...
    def reqPnL(self, reqId: int, account: str, modelCode: str): ...
    def cancelPnL(self, reqId: int): ...
    def reqPnLSingle(self, reqId: int, account: str, modelCode: str, conid: int): ...
    def cancelPnLSingle(self, reqId: int): ...
    def reqExecutions(self, reqId: int, execFilter: ExecutionFilter): ...
    def reqContractDetails(self, reqId: int, contract: Contract): ...
    def reqMktDepthExchanges(self) -> None: ...
    def reqMktDepth(self, reqId: TickerId, contract: Contract, numRows: int, isSmartDepth: bool, mktDepthOptions: TagValueList): ...
    def cancelMktDepth(self, reqId: TickerId, isSmartDepth: bool): ...
    def reqNewsBulletins(self, allMsgs: bool): ...
    def cancelNewsBulletins(self) -> None: ...
    def reqManagedAccts(self): ...
    def requestFA(self, faData: FaDataType): ...
    def replaceFA(self, reqId: TickerId, faData: FaDataType, cxml: str): ...
    def reqHistoricalData(self, reqId: TickerId, contract: Contract, endDateTime: str, durationStr: str, barSizeSetting: str, whatToShow: str, useRTH: int, formatDate: int, keepUpToDate: bool, chartOptions: TagValueList): ...
    def cancelHistoricalData(self, reqId: TickerId): ...
    def reqHeadTimeStamp(self, reqId: TickerId, contract: Contract, whatToShow: str, useRTH: int, formatDate: int): ...
    def cancelHeadTimeStamp(self, reqId: TickerId): ...
    def reqHistogramData(self, tickerId: int, contract: Contract, useRTH: bool, timePeriod: str): ...
    def cancelHistogramData(self, tickerId: int): ...
    def reqHistoricalTicks(self, reqId: int, contract: Contract, startDateTime: str, endDateTime: str, numberOfTicks: int, whatToShow: str, useRth: int, ignoreSize: bool, miscOptions: TagValueList): ...
    def reqScannerParameters(self) -> None: ...
    def reqScannerSubscription(self, reqId: int, subscription: ScannerSubscription, scannerSubscriptionOptions: TagValueList, scannerSubscriptionFilterOptions: TagValueList): ...
    def cancelScannerSubscription(self, reqId: int): ...
    def reqRealTimeBars(self, reqId: TickerId, contract: Contract, barSize: int, whatToShow: str, useRTH: bool, realTimeBarsOptions: TagValueList): ...
    def cancelRealTimeBars(self, reqId: TickerId): ...
    def reqFundamentalData(self, reqId: TickerId, contract: Contract, reportType: str, fundamentalDataOptions: TagValueList): ...
    def cancelFundamentalData(self, reqId: TickerId): ...
    def reqNewsProviders(self) -> None: ...
    def reqNewsArticle(self, reqId: int, providerCode: str, articleId: str, newsArticleOptions: TagValueList): ...
    def reqHistoricalNews(self, reqId: int, conId: int, providerCodes: str, startDateTime: str, endDateTime: str, totalResults: int, historicalNewsOptions: TagValueList): ...
    def queryDisplayGroups(self, reqId: int): ...
    def subscribeToGroupEvents(self, reqId: int, groupId: int): ...
    def updateDisplayGroup(self, reqId: int, contractInfo: str): ...
    def unsubscribeFromGroupEvents(self, reqId: int): ...
    def verifyRequest(self, apiName: str, apiVersion: str): ...
    def verifyMessage(self, apiData: str): ...
    def verifyAndAuthRequest(self, apiName: str, apiVersion: str, opaqueIsvKey: str): ...
    def verifyAndAuthMessage(self, apiData: str, xyzResponse: str): ...
    def reqSecDefOptParams(self, reqId: int, underlyingSymbol: str, futFopExchange: str, underlyingSecType: str, underlyingConId: int): ...
    def reqSoftDollarTiers(self, reqId: int): ...
    def reqFamilyCodes(self) -> None: ...
    def reqMatchingSymbols(self, reqId: int, pattern: str): ...
    def reqCompletedOrders(self, apiOnly: bool): ...
    def reqWshMetaData(self, reqId: int): ...
    def cancelWshMetaData(self, reqId: int): ...
    def reqWshEventData(self, reqId: int, wshEventData: WshEventData, MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS_DATE=None): ...
    def cancelWshEventData(self, reqId: int): ...
    def reqUserInfo(self, reqId: int): ...
