from ibapi.common import *
from ibapi.errors import *
from ibapi.server_versions import *
from _typeshed import Incomplete
from ibapi import comm as comm, decoder as decoder, reader as reader
from ibapi.comm import make_field as make_field, make_field_handle_empty as make_field_handle_empty
from ibapi.connection import Connection as Connection
from ibapi.contract import Contract as Contract
from ibapi.execution import ExecutionFilter as ExecutionFilter
from ibapi.message import OUT as OUT
from ibapi.order import Order as Order
from ibapi.scanner import ScannerSubscription as ScannerSubscription
from ibapi.utils import BadMessage as BadMessage, current_fn_name as current_fn_name

logger: Incomplete

class EClient:
    DISCONNECTED: Incomplete
    CONNECTING: Incomplete
    CONNECTED: Incomplete
    REDIRECT: Incomplete
    msg_queue: Incomplete
    wrapper: Incomplete
    decoder: Incomplete
    def __init__(self, wrapper) -> None: ...
    nKeybIntHard: int
    conn: Incomplete
    host: Incomplete
    port: Incomplete
    extraAuth: bool
    clientId: Incomplete
    serverVersion_: Incomplete
    connTime: Incomplete
    connState: Incomplete
    optCapab: str
    asynchronous: bool
    reader: Incomplete
    decode: Incomplete
    connectionOptions: Incomplete
    def reset(self) -> None: ...
    def setConnState(self, connState) -> None: ...
    def sendMsg(self, msg) -> None: ...
    def logRequest(self, fnName, fnParams) -> None: ...
    def startApi(self) -> None: ...
    def connect(self, host, port, clientId) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self): ...
    def keyboardInterrupt(self) -> None: ...
    def keyboardInterruptHard(self) -> None: ...
    def setConnectionOptions(self, opts) -> None: ...
    def msgLoopTmo(self) -> None: ...
    def msgLoopRec(self) -> None: ...
    def run(self) -> None: ...
    def reqCurrentTime(self) -> None: ...
    def serverVersion(self): ...
    def setServerLogLevel(self, logLevel: int): ...
    def twsConnectionTime(self): ...
    def reqMktData(self, reqId: TickerId, contract: Contract, genericTickList: str, snapshot: bool, regulatorySnapshot: bool, mktDataOptions: TagValueList): ...
    def cancelMktData(self, reqId: TickerId): ...
    def reqMarketDataType(self, marketDataType: int): ...
    def reqSmartComponents(self, reqId: int, bboExchange: str): ...
    def reqMarketRule(self, marketRuleId: int): ...
    def reqTickByTickData(self, reqId: int, contract: Contract, tickType: str, numberOfTicks: int, ignoreSize: bool): ...
    def cancelTickByTickData(self, reqId: int): ...
    def calculateImpliedVolatility(self, reqId: TickerId, contract: Contract, optionPrice: float, underPrice: float, implVolOptions: TagValueList): ...
    def cancelCalculateImpliedVolatility(self, reqId: TickerId): ...
    def calculateOptionPrice(self, reqId: TickerId, contract: Contract, volatility: float, underPrice: float, optPrcOptions: TagValueList): ...
    def cancelCalculateOptionPrice(self, reqId: TickerId): ...
    def exerciseOptions(self, reqId: TickerId, contract: Contract, exerciseAction: int, exerciseQuantity: int, account: str, override: int): ...
    def placeOrder(self, orderId: OrderId, contract: Contract, order: Order): ...
    def cancelOrder(self, orderId: OrderId): ...
    def reqOpenOrders(self) -> None: ...
    def reqAutoOpenOrders(self, bAutoBind: bool): ...
    def reqAllOpenOrders(self) -> None: ...
    def reqGlobalCancel(self) -> None: ...
    def reqIds(self, numIds: int): ...
    def reqAccountUpdates(self, subscribe: bool, acctCode: str): ...
    def reqAccountSummary(self, reqId: int, groupName: str, tags: str): ...
    def cancelAccountSummary(self, reqId: int): ...
    def reqPositions(self) -> None: ...
    def cancelPositions(self) -> None: ...
    def reqPositionsMulti(self, reqId: int, account: str, modelCode: str): ...
    def cancelPositionsMulti(self, reqId: int): ...
    def reqAccountUpdatesMulti(self, reqId: int, account: str, modelCode: str, ledgerAndNLV: bool): ...
    def cancelAccountUpdatesMulti(self, reqId: int): ...
    def reqPnL(self, reqId: int, account: str, modelCode: str): ...
    def cancelPnL(self, reqId: int): ...
    def reqPnLSingle(self, reqId: int, account: str, modelCode: str, conid: int): ...
    def cancelPnLSingle(self, reqId: int): ...
    def reqExecutions(self, reqId: int, execFilter: ExecutionFilter): ...
    def reqContractDetails(self, reqId: int, contract: Contract): ...
    def reqMktDepthExchanges(self) -> None: ...
    def reqMktDepth(self, reqId: TickerId, contract: Contract, numRows: int, isSmartDepth: bool, mktDepthOptions: TagValueList): ...
    def cancelMktDepth(self, reqId: TickerId, isSmartDepth: bool): ...
    def reqNewsBulletins(self, allMsgs: bool): ...
    def cancelNewsBulletins(self) -> None: ...
    def reqManagedAccts(self): ...
    def requestFA(self, faData: FaDataType): ...
    def replaceFA(self, reqId: TickerId, faData: FaDataType, cxml: str): ...
    def reqHistoricalData(self, reqId: TickerId, contract: Contract, endDateTime: str, durationStr: str, barSizeSetting: str, whatToShow: str, useRTH: int, formatDate: int, keepUpToDate: bool, chartOptions: TagValueList): ...
    def cancelHistoricalData(self, reqId: TickerId): ...
    def reqHeadTimeStamp(self, reqId: TickerId, contract: Contract, whatToShow: str, useRTH: int, formatDate: int): ...
    def cancelHeadTimeStamp(self, reqId: TickerId): ...
    def reqHistogramData(self, tickerId: int, contract: Contract, useRTH: bool, timePeriod: str): ...
    def cancelHistogramData(self, tickerId: int): ...
    def reqHistoricalTicks(self, reqId: int, contract: Contract, startDateTime: str, endDateTime: str, numberOfTicks: int, whatToShow: str, useRth: int, ignoreSize: bool, miscOptions: TagValueList): ...
    def reqScannerParameters(self) -> None: ...
    def reqScannerSubscription(self, reqId: int, subscription: ScannerSubscription, scannerSubscriptionOptions: TagValueList, scannerSubscriptionFilterOptions: TagValueList): ...
    def cancelScannerSubscription(self, reqId: int): ...
    def reqRealTimeBars(self, reqId: TickerId, contract: Contract, barSize: int, whatToShow: str, useRTH: bool, realTimeBarsOptions: TagValueList): ...
    def cancelRealTimeBars(self, reqId: TickerId): ...
    def reqFundamentalData(self, reqId: TickerId, contract: Contract, reportType: str, fundamentalDataOptions: TagValueList): ...
    def cancelFundamentalData(self, reqId: TickerId): ...
    def reqNewsProviders(self) -> None: ...
    def reqNewsArticle(self, reqId: int, providerCode: str, articleId: str, newsArticleOptions: TagValueList): ...
    def reqHistoricalNews(self, reqId: int, conId: int, providerCodes: str, startDateTime: str, endDateTime: str, totalResults: int, historicalNewsOptions: TagValueList): ...
    def queryDisplayGroups(self, reqId: int): ...
    def subscribeToGroupEvents(self, reqId: int, groupId: int): ...
    def updateDisplayGroup(self, reqId: int, contractInfo: str): ...
    def unsubscribeFromGroupEvents(self, reqId: int): ...
    def verifyRequest(self, apiName: str, apiVersion: str): ...
    def verifyMessage(self, apiData: str): ...
    def verifyAndAuthRequest(self, apiName: str, apiVersion: str, opaqueIsvKey: str): ...
    def verifyAndAuthMessage(self, apiData: str, xyzResponse: str): ...
    def reqSecDefOptParams(self, reqId: int, underlyingSymbol: str, futFopExchange: str, underlyingSecType: str, underlyingConId: int): ...
    def reqSoftDollarTiers(self, reqId: int): ...
    def reqFamilyCodes(self) -> None: ...
    def reqMatchingSymbols(self, reqId: int, pattern: str): ...
    def reqCompletedOrders(self, apiOnly: bool): ...
