from _typeshed import Incomplete
from decimal import Decimal
from ibapi.client import EClient as EClient
from ibapi.common import BarData as BarData, OrderId as OrderId, TickerId as TickerId
from ibapi.contract import Contract as Contract, ContractDetails as ContractDetails
from ibapi.execution import Execution as Execution, ExecutionFilter as ExecutionFilter
from ibapi.order import Order as Order
from ibapi.order_cancel import OrderCancel as OrderCancel
from ibapi.order_state import OrderState as OrderState
from ibapi.wrapper import EWrapper as EWrapper

class ResponseTimeout(Exception): ...

class TWSSyncWrapper(EWrapper, EClient):
    timeout: Incomplete
    response_events: Incomplete
    response_data: Incomplete
    contract_details: Incomplete
    order_status: Incomplete
    open_orders: Incomplete
    executions: Incomplete
    portfolio: Incomplete
    positions: Incomplete
    account_summary: Incomplete
    market_data: Incomplete
    historical_data: Incomplete
    current_time_value: Incomplete
    next_valid_id_value: Incomplete
    completion_events: Incomplete
    errors: Incomplete
    def __init__(self, timeout: int = 30) -> None: ...
    api_thread: Incomplete
    def connect_and_start(self, host, port, client_id): ...
    def nextValidId(self, orderId: int): ...
    def error(self, reqId: TickerId, errorTime: int, errorCode: int, errorString: str, advancedOrderRejectJson: str = ''): ...
    def currentTime(self, time_value: int): ...
    def contractDetails(self, reqId: int, contractDetails: ContractDetails): ...
    def contractDetailsEnd(self, reqId: int): ...
    def orderStatus(self, orderId: OrderId, status: str, filled: Decimal, remaining: Decimal, avgFillPrice: float, permId: int, parentId: int, lastFillPrice: float, clientId: int, whyHeld: str, mktCapPrice: float): ...
    def openOrder(self, orderId: OrderId, contract: Contract, order: Order, orderState: OrderState): ...
    def openOrderEnd(self) -> None: ...
    def execDetails(self, reqId: int, contract: Contract, execution: Execution): ...
    def execDetailsEnd(self, reqId: int): ...
    def updatePortfolio(self, contract: Contract, position: Decimal, marketPrice: float, marketValue: float, averageCost: float, unrealizedPNL: float, realizedPNL: float, accountName: str): ...
    def accountDownloadEnd(self, accountName: str): ...
    def position(self, account: str, contract: Contract, position: Decimal, avgCost: float): ...
    def positionEnd(self) -> None: ...
    def accountSummary(self, reqId: int, account: str, tag: str, value: str, currency: str): ...
    def accountSummaryEnd(self, reqId: int): ...
    def tickPrice(self, reqId: TickerId, tickType: int, price: float, attrib): ...
    def tickSize(self, reqId: TickerId, tickType: int, size: Decimal): ...
    def tickSnapshotEnd(self, reqId: int): ...
    def historicalData(self, reqId: int, bar: BarData): ...
    def historicalDataEnd(self, reqId: int, start: str, end: str): ...
    def get_next_valid_id(self, timeout=None): ...
    def get_current_time(self, timeout: int = 1): ...
    def get_contract_details(self, contract, timeout: int = 5): ...
    def place_order_sync(self, contract, order, timeout=None): ...
    def cancel_order_sync(self, order_id, orderCancel=None, timeout: int = 3): ...
    def get_open_orders(self, timeout: int = 3): ...
    def get_executions(self, exec_filter=None, timeout: int = 10): ...
    def get_portfolio(self, account_code: str = '', timeout=None): ...
    def get_positions(self, timeout: int = 10): ...
    def get_account_summary(self, tags, group: str = 'All', timeout: int = 5): ...
    def get_market_data_snapshot(self, contract, generic_tick_list: str = '', snapshot: bool = True, timeout=None): ...
    def get_historical_data(self, contract, end_date_time, duration_str, bar_size_setting, what_to_show, use_rth: bool = True, format_date: int = 1, timeout: int = 30): ...
    def disconnect_and_stop(self) -> None: ...
