from _typeshed import Incomplete
from decimal import Decimal
from ibapi.const import DOUBLE_INFINITY as DOUBLE_INFINITY, INFINITY_STR as INFINITY_STR, UNSET_DECIMAL as UNSET_DECIMAL, UNSET_DOUBLE as UNSET_DOUBLE, UNSET_INTEGER as UNSET_INTEGER, UNSET_LONG as UNSET_LONG

logger: Incomplete

def iswrapper(fn): ...

class BadMessage(Exception):
    text: Incomplete
    def __init__(self, text) -> None: ...

class ClientException(Exception):
    code: Incomplete
    msg: Incomplete
    text: Incomplete
    def __init__(self, code, msg, text) -> None: ...

class LogFunction:
    text: Incomplete
    logLevel: Incomplete
    def __init__(self, text, logLevel) -> None: ...
    def __call__(self, fn): ...

def current_fn_name(parent_idx: int = 0): ...
def setattr_log(self, var_name, var_value) -> None: ...

SHOW_UNSET: bool

def decode(the_type, fields, show_unset: bool = False, use_unicode: bool = False): ...
def ExerciseStaticMethods(klass) -> None: ...
def isValidFloatValue(val: float) -> bool: ...
def isValidIntValue(val: int) -> bool: ...
def isValidLongValue(val: int) -> bool: ...
def isValidDecimalValue(val: Decimal) -> bool: ...
def floatMaxString(val: float): ...
def longMaxString(val): ...
def intMaxString(val): ...
def isAsciiPrintable(val): ...
def decimalMaxString(val: Decimal): ...
def isPegBenchOrder(orderType: str): ...
def isPegMidOrder(orderType: str): ...
def isPegBestOrder(orderType: str): ...
def log_(func, params, action) -> None: ...
def currentTimeMillis(): ...
def getTimeStrFromMillis(time: int): ...
def listOfValues(cls): ...
def getEnumTypeFromString(cls, stringIn): ...
def getEnumTypeName(cls, valueIn): ...
