from _typeshed import Incomplete
from ibapi.common import UNSET_DOUBLE as UNSET_DOUBLE, UNSET_INTEGER as UNSET_INTEGER

logger: Incomplete

def iswrapper(fn): ...

class BadMessage(Exception):
    text: Incomplete
    def __init__(self, text) -> None: ...

class LogFunction:
    text: Incomplete
    logLevel: Incomplete
    def __init__(self, text, logLevel) -> None: ...
    def __call__(self, fn): ...

def current_fn_name(parent_idx: int = 0): ...
def setattr_log(self, var_name, var_value) -> None: ...

SHOW_UNSET: bool

def decode(the_type, fields, show_unset: bool = False): ...
def ExerciseStaticMethods(klass) -> None: ...
def floatToStr(val): ...
