from ibapi.wrapper import *
from ibapi.server_versions import *
from ibapi.utils import *
from ibapi.ticktype import *
from ibapi.common import *
from ibapi.decoder_utils import *
from _typeshed import Incomplete
from ibapi.common import PROTOBUF_MSG_ID as PROTOBUF_MSG_ID
from ibapi.const import NO_VALID_ID as NO_VALID_ID
from ibapi.contract import ContractDescription as ContractDescription, FundAssetType as FundAssetType, FundDistributionPolicyIndicator as FundDistributionPolicyIndicator, getEnumTypeFromString as getEnumTypeFromString
from ibapi.errors import BAD_MESSAGE as BAD_MESSAGE
from ibapi.ineligibility_reason import IneligibilityReason as IneligibilityReason
from ibapi.message import IN as IN
from ibapi.orderdecoder import OrderDecoder as OrderDecoder
from ibapi.scanner import ScanData as ScanData
from ibapi.softdollartier import SoftDollarTier as SoftDollarTier
from ibapi.tag_value import TagValue as TagValue

logger: Incomplete

class HandleInfo(Object):
    wrapperMeth: Incomplete
    wrapperParams: Incomplete
    processMeth: Incomplete
    def __init__(self, wrap=None, proc=None) -> None: ...

class Decoder(Object):
    wrapper: Incomplete
    serverVersion: Incomplete
    def __init__(self, wrapper, serverVersion) -> None: ...
    def processTickPriceMsg(self, fields) -> None: ...
    def processTickSizeMsg(self, fields) -> None: ...
    def processOrderStatusMsg(self, fields) -> None: ...
    def processOpenOrder(self, fields) -> None: ...
    def processPortfolioValueMsg(self, fields) -> None: ...
    def processContractDataMsg(self, fields) -> None: ...
    def processBondContractDataMsg(self, fields) -> None: ...
    def processScannerDataMsg(self, fields) -> None: ...
    def processExecutionDataMsg(self, fields) -> None: ...
    def processExecutionDataEndMsgProtoBuf(self, protobuf) -> None: ...
    def processExecutionDataMsgProtoBuf(self, protobuf) -> None: ...
    def processHistoricalDataMsg(self, fields) -> None: ...
    def processHistoricalDataEndMsg(self, fields) -> None: ...
    def processHistoricalDataUpdateMsg(self, fields) -> None: ...
    def processRealTimeBarMsg(self, fields) -> None: ...
    def processTickOptionComputationMsg(self, fields) -> None: ...
    def processDeltaNeutralValidationMsg(self, fields) -> None: ...
    def processMarketDataTypeMsg(self, fields) -> None: ...
    def processCommissionAndFeesReportMsg(self, fields) -> None: ...
    def processPositionDataMsg(self, fields) -> None: ...
    def processPositionMultiMsg(self, fields) -> None: ...
    def processSecurityDefinitionOptionParameterMsg(self, fields) -> None: ...
    def processSecurityDefinitionOptionParameterEndMsg(self, fields) -> None: ...
    def processSoftDollarTiersMsg(self, fields) -> None: ...
    def processFamilyCodesMsg(self, fields) -> None: ...
    def processSymbolSamplesMsg(self, fields) -> None: ...
    def processSmartComponents(self, fields) -> None: ...
    def processTickReqParams(self, fields) -> None: ...
    def processMktDepthExchanges(self, fields) -> None: ...
    def processHeadTimestamp(self, fields) -> None: ...
    def processTickNews(self, fields) -> None: ...
    def processNewsProviders(self, fields) -> None: ...
    def processNewsArticle(self, fields) -> None: ...
    def processHistoricalNews(self, fields) -> None: ...
    def processHistoricalNewsEnd(self, fields) -> None: ...
    def processHistogramData(self, fields) -> None: ...
    def processRerouteMktDataReq(self, fields) -> None: ...
    def processRerouteMktDepthReq(self, fields) -> None: ...
    def processMarketRuleMsg(self, fields) -> None: ...
    def processPnLMsg(self, fields) -> None: ...
    def processPnLSingleMsg(self, fields) -> None: ...
    def processHistoricalTicks(self, fields) -> None: ...
    def processHistoricalTicksBidAsk(self, fields) -> None: ...
    def processHistoricalTicksLast(self, fields) -> None: ...
    def processTickByTickMsg(self, fields) -> None: ...
    def processOrderBoundMsg(self, fields) -> None: ...
    def processMarketDepthMsg(self, fields) -> None: ...
    def processMarketDepthL2Msg(self, fields) -> None: ...
    def processCompletedOrderMsg(self, fields) -> None: ...
    def processCompletedOrdersEndMsg(self, fields) -> None: ...
    def processReplaceFAEndMsg(self, fields) -> None: ...
    def processWshMetaDataMsg(self, fields) -> None: ...
    def processWshEventDataMsg(self, fields) -> None: ...
    def processHistoricalSchedule(self, fields) -> None: ...
    def processUserInfo(self, fields) -> None: ...
    def processCurrentTimeInMillis(self, fields) -> None: ...
    def processErrorMsg(self, fields) -> None: ...
    def readLastTradeDate(self, fields, contract: ContractDetails, isBond: bool): ...
    def discoverParams(self) -> None: ...
    def printParams(self) -> None: ...
    def interpretWithSignature(self, fields, handleInfo): ...
    def interpret(self, fields, msgId) -> None: ...
    def processProtoBuf(self, protoBuf, msgId) -> None: ...
    msgId2handleInfo: Incomplete
    msgId2handleInfoProtoBuf: Incomplete
