from ibapi.wrapper import *
from ibapi.server_versions import *
from ibapi.utils import *
from ibapi.ticktype import *
from ibapi.common import *
from _typeshed import Incomplete
from ibapi.common import PROTOBUF_MSG_ID as PROTOBUF_MSG_ID
from ibapi.const import NO_VALID_ID as NO_VALID_ID
from ibapi.contract import ContractDescription as ContractDescription, FundAssetType as FundAssetType, FundDistributionPolicyIndicator as FundDistributionPolicyIndicator
from ibapi.decoder_utils import decodeContract as decodeContract, decodeContractDetails as decodeContractDetails, decodeExecution as decodeExecution, decodeHistogramDataEntry as decodeHistogramDataEntry, decodeHistoricalDataBar as decodeHistoricalDataBar, decodeHistoricalTick as decodeHistoricalTick, decodeHistoricalTickBidAsk as decodeHistoricalTickBidAsk, decodeHistoricalTickLast as decodeHistoricalTickLast, decodeOrder as decodeOrder, decodeOrderState as decodeOrderState, setLastTradeDate as setLastTradeDate
from ibapi.errors import BAD_MESSAGE as BAD_MESSAGE, UNKNOWN_ID as UNKNOWN_ID
from ibapi.ineligibility_reason import IneligibilityReason as IneligibilityReason
from ibapi.message import IN as IN
from ibapi.orderdecoder import OrderDecoder as OrderDecoder
from ibapi.scanner import ScanData as ScanData
from ibapi.softdollartier import SoftDollarTier as SoftDollarTier
from ibapi.tag_value import TagValue as TagValue
from ibapi.utils import getEnumTypeFromString as getEnumTypeFromString

logger: Incomplete

class HandleInfo(Object):
    wrapperMeth: Incomplete
    wrapperParams: Incomplete
    processMeth: Incomplete
    def __init__(self, wrap=None, proc=None) -> None: ...

class Decoder(Object):
    wrapper: Incomplete
    serverVersion: Incomplete
    def __init__(self, wrapper, serverVersion) -> None: ...
    def processTickPriceMsg(self, fields) -> None: ...
    def processTickPriceMsgProtoBuf(self, protobuf) -> None: ...
    def processTickSizeMsg(self, fields) -> None: ...
    def processTickSizeMsgProtoBuf(self, protobuf) -> None: ...
    def processOrderStatusMsg(self, fields) -> None: ...
    def processOrderStatusMsgProtoBuf(self, protobuf) -> None: ...
    def processOpenOrder(self, fields) -> None: ...
    def processOpenOrderMsgProtoBuf(self, protobuf) -> None: ...
    def processOpenOrdersEndMsgProtoBuf(self, protobuf) -> None: ...
    def processPortfolioValueMsg(self, fields) -> None: ...
    def processPortfolioValueMsgProtoBuf(self, protobuf) -> None: ...
    def processContractDataMsg(self, fields) -> None: ...
    def processContractDataMsgProtoBuf(self, protobuf) -> None: ...
    def processBondContractDataMsg(self, fields) -> None: ...
    def processBondContractDataMsgProtoBuf(self, protobuf) -> None: ...
    def processContractDataEndMsgProtoBuf(self, protobuf) -> None: ...
    def processScannerDataMsg(self, fields) -> None: ...
    def processExecutionDataMsg(self, fields) -> None: ...
    def processExecutionDataEndMsgProtoBuf(self, protobuf) -> None: ...
    def processExecutionDataMsgProtoBuf(self, protobuf) -> None: ...
    def processHistoricalDataMsg(self, fields) -> None: ...
    def processHistoricalDataMsgProtoBuf(self, protobuf) -> None: ...
    def processHistoricalDataEndMsg(self, fields) -> None: ...
    def processHistoricalDataEndMsgProtoBuf(self, protobuf) -> None: ...
    def processHistoricalDataUpdateMsg(self, fields) -> None: ...
    def processHistoricalDataUpdateMsgProtoBuf(self, protobuf) -> None: ...
    def processRealTimeBarMsg(self, fields) -> None: ...
    def processRealTimeBarMsgProtoBuf(self, protobuf) -> None: ...
    def processTickOptionComputationMsg(self, fields) -> None: ...
    def processTickOptionComputationMsgProtoBuf(self, protobuf) -> None: ...
    def processDeltaNeutralValidationMsg(self, fields) -> None: ...
    def processMarketDataTypeMsg(self, fields) -> None: ...
    def processMarketDataTypeMsgProtoBuf(self, protobuf) -> None: ...
    def processCommissionAndFeesReportMsg(self, fields) -> None: ...
    def processPositionDataMsg(self, fields) -> None: ...
    def processPositionMsgProtoBuf(self, protobuf) -> None: ...
    def processPositionMultiMsg(self, fields) -> None: ...
    def processPositionMultiMsgProtoBuf(self, protobuf) -> None: ...
    def processSecurityDefinitionOptionParameterMsg(self, fields) -> None: ...
    def processSecurityDefinitionOptionParameterEndMsg(self, fields) -> None: ...
    def processSoftDollarTiersMsg(self, fields) -> None: ...
    def processFamilyCodesMsg(self, fields) -> None: ...
    def processSymbolSamplesMsg(self, fields) -> None: ...
    def processSmartComponents(self, fields) -> None: ...
    def processTickReqParams(self, fields) -> None: ...
    def processTickReqParamsMsgProtoBuf(self, protobuf) -> None: ...
    def processMktDepthExchanges(self, fields) -> None: ...
    def processHeadTimestamp(self, fields) -> None: ...
    def processHeadTimestampMsgProtoBuf(self, protobuf) -> None: ...
    def processTickNews(self, fields) -> None: ...
    def processNewsProviders(self, fields) -> None: ...
    def processNewsArticle(self, fields) -> None: ...
    def processHistoricalNews(self, fields) -> None: ...
    def processHistoricalNewsEnd(self, fields) -> None: ...
    def processHistogramData(self, fields) -> None: ...
    def processHistogramDataMsgProtoBuf(self, protobuf) -> None: ...
    def processRerouteMktDataReq(self, fields) -> None: ...
    def processRerouteMktDepthReq(self, fields) -> None: ...
    def processMarketRuleMsg(self, fields) -> None: ...
    def processPnLMsg(self, fields) -> None: ...
    def processPnLSingleMsg(self, fields) -> None: ...
    def processHistoricalTicks(self, fields) -> None: ...
    def processHistoricalTicksMsgProtoBuf(self, protobuf) -> None: ...
    def processHistoricalTicksBidAsk(self, fields) -> None: ...
    def processHistoricalTicksBidAskMsgProtoBuf(self, protobuf) -> None: ...
    def processHistoricalTicksLast(self, fields) -> None: ...
    def processHistoricalTicksLastMsgProtoBuf(self, protobuf) -> None: ...
    def processTickByTickMsg(self, fields) -> None: ...
    def processTickByTickMsgProtoBuf(self, protobuf) -> None: ...
    def processOrderBoundMsg(self, fields) -> None: ...
    def processOrderBoundMsgProtoBuf(self, protobuf) -> None: ...
    def processMarketDepthMsg(self, fields) -> None: ...
    def processMarketDepthMsgProtoBuf(self, protobuf) -> None: ...
    def processMarketDepthL2Msg(self, fields) -> None: ...
    def processMarketDepthL2MsgProtoBuf(self, protobuf) -> None: ...
    def processCompletedOrderMsg(self, fields) -> None: ...
    def processCompletedOrderMsgProtoBuf(self, protobuf) -> None: ...
    def processCompletedOrdersEndMsg(self, fields) -> None: ...
    def processCompletedOrdersEndMsgProtoBuf(self, protobuf) -> None: ...
    def processReplaceFAEndMsg(self, fields) -> None: ...
    def processWshMetaDataMsg(self, fields) -> None: ...
    def processWshEventDataMsg(self, fields) -> None: ...
    def processHistoricalSchedule(self, fields) -> None: ...
    def processUserInfo(self, fields) -> None: ...
    def processCurrentTimeInMillis(self, fields) -> None: ...
    def processErrorMsg(self, fields) -> None: ...
    def processErrorMsgProtoBuf(self, protobuf) -> None: ...
    def processTickStringMsgProtoBuf(self, protobuf) -> None: ...
    def processTickGenericMsgProtoBuf(self, protobuf) -> None: ...
    def processTickSnapshotEndMsgProtoBuf(self, protobuf) -> None: ...
    def processAccountValueMsgProtoBuf(self, protobuf) -> None: ...
    def processAcctUpdateTimeMsgProtoBuf(self, protobuf) -> None: ...
    def processAccountDataEndMsgProtoBuf(self, protobuf) -> None: ...
    def processManagedAccountsMsgProtoBuf(self, protobuf) -> None: ...
    def processPositionEndMsgProtoBuf(self, protobuf) -> None: ...
    def processAccountSummaryMsgProtoBuf(self, protobuf) -> None: ...
    def processAccountSummaryEndMsgProtoBuf(self, protobuf) -> None: ...
    def processPositionMultiEndMsgProtoBuf(self, protobuf) -> None: ...
    def processAccountUpdateMultiMsgProtoBuf(self, protobuf) -> None: ...
    def processAccountUpdateMultiEndMsgProtoBuf(self, protobuf) -> None: ...
    def readLastTradeDate(self, fields, contract: ContractDetails, isBond: bool): ...
    def discoverParams(self) -> None: ...
    def printParams(self) -> None: ...
    def interpretWithSignature(self, fields, handleInfo): ...
    def interpret(self, fields, msgId) -> None: ...
    def processProtoBuf(self, protoBuf, msgId) -> None: ...
    msgId2handleInfo: Incomplete
    msgId2handleInfoProtoBuf: Incomplete
