from _typeshed import Incomplete
from decimal import Decimal
from ibapi.commission_report import CommissionReport as CommissionReport
from ibapi.common import BarData as BarData, FaDataType as FaDataType, HistogramData as HistogramData, ListOfContractDescription as ListOfContractDescription, ListOfDepthExchanges as ListOfDepthExchanges, ListOfFamilyCode as ListOfFamilyCode, ListOfHistoricalSessions as ListOfHistoricalSessions, ListOfHistoricalTick as ListOfHistoricalTick, ListOfHistoricalTickBidAsk as ListOfHistoricalTickBidAsk, ListOfHistoricalTickLast as ListOfHistoricalTickLast, ListOfNewsProviders as ListOfNewsProviders, ListOfPriceIncrements as ListOfPriceIncrements, OrderId as OrderId, SetOfFloat as SetOfFloat, SetOfString as SetOfString, SmartComponentMap as SmartComponentMap, TickAttrib as TickAttrib, TickAttribBidAsk as TickAttribBidAsk, TickAttribLast as TickAttribLast, TickerId as TickerId
from ibapi.contract import Contract as Contract, ContractDetails as ContractDetails, DeltaNeutralContract as DeltaNeutralContract
from ibapi.execution import Execution as Execution
from ibapi.order import Order as Order
from ibapi.order_state import OrderState as OrderState
from ibapi.ticktype import TickType as TickType
from ibapi.utils import current_fn_name as current_fn_name, log_ as log_

logger: Incomplete

def logAnswer(fnName, fnParams) -> None: ...

class EWrapper:
    def __init__(self) -> None: ...
    def error(self, reqId: TickerId, errorCode: int, errorString: str, advancedOrderRejectJson: str = ''): ...
    def winError(self, text: str, lastError: int): ...
    def connectAck(self) -> None: ...
    def marketDataType(self, reqId: TickerId, marketDataType: int): ...
    def tickPrice(self, reqId: TickerId, tickType: TickType, price: float, attrib: TickAttrib): ...
    def tickSize(self, reqId: TickerId, tickType: TickType, size: Decimal): ...
    def tickSnapshotEnd(self, reqId: int): ...
    def tickGeneric(self, reqId: TickerId, tickType: TickType, value: float): ...
    def tickString(self, reqId: TickerId, tickType: TickType, value: str): ...
    def tickEFP(self, reqId: TickerId, tickType: TickType, basisPoints: float, formattedBasisPoints: str, totalDividends: float, holdDays: int, futureLastTradeDate: str, dividendImpact: float, dividendsToLastTradeDate: float): ...
    def orderStatus(self, orderId: OrderId, status: str, filled: Decimal, remaining: Decimal, avgFillPrice: float, permId: int, parentId: int, lastFillPrice: float, clientId: int, whyHeld: str, mktCapPrice: float): ...
    def openOrder(self, orderId: OrderId, contract: Contract, order: Order, orderState: OrderState): ...
    def openOrderEnd(self) -> None: ...
    def connectionClosed(self) -> None: ...
    def updateAccountValue(self, key: str, val: str, currency: str, accountName: str): ...
    def updatePortfolio(self, contract: Contract, position: Decimal, marketPrice: float, marketValue: float, averageCost: float, unrealizedPNL: float, realizedPNL: float, accountName: str): ...
    def updateAccountTime(self, timeStamp: str): ...
    def accountDownloadEnd(self, accountName: str): ...
    def nextValidId(self, orderId: int): ...
    def contractDetails(self, reqId: int, contractDetails: ContractDetails): ...
    def bondContractDetails(self, reqId: int, contractDetails: ContractDetails): ...
    def contractDetailsEnd(self, reqId: int): ...
    def execDetails(self, reqId: int, contract: Contract, execution: Execution): ...
    def execDetailsEnd(self, reqId: int): ...
    def updateMktDepth(self, reqId: TickerId, position: int, operation: int, side: int, price: float, size: Decimal): ...
    def updateMktDepthL2(self, reqId: TickerId, position: int, marketMaker: str, operation: int, side: int, price: float, size: Decimal, isSmartDepth: bool): ...
    def updateNewsBulletin(self, msgId: int, msgType: int, newsMessage: str, originExch: str): ...
    def managedAccounts(self, accountsList: str): ...
    def receiveFA(self, faData: FaDataType, cxml: str): ...
    def historicalData(self, reqId: int, bar: BarData): ...
    def historicalDataEnd(self, reqId: int, start: str, end: str): ...
    def scannerParameters(self, xml: str): ...
    def scannerData(self, reqId: int, rank: int, contractDetails: ContractDetails, distance: str, benchmark: str, projection: str, legsStr: str): ...
    def scannerDataEnd(self, reqId: int): ...
    def realtimeBar(self, reqId: TickerId, time: int, open_: float, high: float, low: float, close: float, volume: Decimal, wap: Decimal, count: int): ...
    def currentTime(self, time: int): ...
    def fundamentalData(self, reqId: TickerId, data: str): ...
    def deltaNeutralValidation(self, reqId: int, deltaNeutralContract: DeltaNeutralContract): ...
    def commissionReport(self, commissionReport: CommissionReport): ...
    def position(self, account: str, contract: Contract, position: Decimal, avgCost: float): ...
    def positionEnd(self) -> None: ...
    def accountSummary(self, reqId: int, account: str, tag: str, value: str, currency: str): ...
    def accountSummaryEnd(self, reqId: int): ...
    def verifyMessageAPI(self, apiData: str): ...
    def verifyCompleted(self, isSuccessful: bool, errorText: str): ...
    def verifyAndAuthMessageAPI(self, apiData: str, xyzChallange: str): ...
    def verifyAndAuthCompleted(self, isSuccessful: bool, errorText: str): ...
    def displayGroupList(self, reqId: int, groups: str): ...
    def displayGroupUpdated(self, reqId: int, contractInfo: str): ...
    def positionMulti(self, reqId: int, account: str, modelCode: str, contract: Contract, pos: Decimal, avgCost: float): ...
    def positionMultiEnd(self, reqId: int): ...
    def accountUpdateMulti(self, reqId: int, account: str, modelCode: str, key: str, value: str, currency: str): ...
    def accountUpdateMultiEnd(self, reqId: int): ...
    def tickOptionComputation(self, reqId: TickerId, tickType: TickType, tickAttrib: int, impliedVol: float, delta: float, optPrice: float, pvDividend: float, gamma: float, vega: float, theta: float, undPrice: float): ...
    def securityDefinitionOptionParameter(self, reqId: int, exchange: str, underlyingConId: int, tradingClass: str, multiplier: str, expirations: SetOfString, strikes: SetOfFloat): ...
    def securityDefinitionOptionParameterEnd(self, reqId: int): ...
    def softDollarTiers(self, reqId: int, tiers: list): ...
    def familyCodes(self, familyCodes: ListOfFamilyCode): ...
    def symbolSamples(self, reqId: int, contractDescriptions: ListOfContractDescription): ...
    def mktDepthExchanges(self, depthMktDataDescriptions: ListOfDepthExchanges): ...
    def tickNews(self, tickerId: int, timeStamp: int, providerCode: str, articleId: str, headline: str, extraData: str): ...
    def smartComponents(self, reqId: int, smartComponentMap: SmartComponentMap): ...
    def tickReqParams(self, tickerId: int, minTick: float, bboExchange: str, snapshotPermissions: int): ...
    def newsProviders(self, newsProviders: ListOfNewsProviders): ...
    def newsArticle(self, requestId: int, articleType: int, articleText: str): ...
    def historicalNews(self, requestId: int, time: str, providerCode: str, articleId: str, headline: str): ...
    def historicalNewsEnd(self, requestId: int, hasMore: bool): ...
    def headTimestamp(self, reqId: int, headTimestamp: str): ...
    def histogramData(self, reqId: int, items: HistogramData): ...
    def historicalDataUpdate(self, reqId: int, bar: BarData): ...
    def rerouteMktDataReq(self, reqId: int, conId: int, exchange: str): ...
    def rerouteMktDepthReq(self, reqId: int, conId: int, exchange: str): ...
    def marketRule(self, marketRuleId: int, priceIncrements: ListOfPriceIncrements): ...
    def pnl(self, reqId: int, dailyPnL: float, unrealizedPnL: float, realizedPnL: float): ...
    def pnlSingle(self, reqId: int, pos: Decimal, dailyPnL: float, unrealizedPnL: float, realizedPnL: float, value: float): ...
    def historicalTicks(self, reqId: int, ticks: ListOfHistoricalTick, done: bool): ...
    def historicalTicksBidAsk(self, reqId: int, ticks: ListOfHistoricalTickBidAsk, done: bool): ...
    def historicalTicksLast(self, reqId: int, ticks: ListOfHistoricalTickLast, done: bool): ...
    def tickByTickAllLast(self, reqId: int, tickType: int, time: int, price: float, size: Decimal, tickAttribLast: TickAttribLast, exchange: str, specialConditions: str): ...
    def tickByTickBidAsk(self, reqId: int, time: int, bidPrice: float, askPrice: float, bidSize: Decimal, askSize: Decimal, tickAttribBidAsk: TickAttribBidAsk): ...
    def tickByTickMidPoint(self, reqId: int, time: int, midPoint: float): ...
    def orderBound(self, permId: int, clientId: int, orderId: int): ...
    def completedOrder(self, contract: Contract, order: Order, orderState: OrderState): ...
    def completedOrdersEnd(self) -> None: ...
    def replaceFAEnd(self, reqId: int, text: str): ...
    def wshMetaData(self, reqId: int, dataJson: str): ...
    def wshEventData(self, reqId: int, dataJson: str): ...
    def historicalSchedule(self, reqId: int, startDateTime: str, endDateTime: str, timeZone: str, sessions: ListOfHistoricalSessions): ...
    def userInfo(self, reqId: int, whiteBrandingId: str): ...
