from _typeshed import Incomplete
from ibapi.common import UNSET_DOUBLE as UNSET_DOUBLE, UNSET_INTEGER as UNSET_INTEGER

logger: Incomplete

def make_msg(text) -> bytes: ...
def make_field(val) -> str: ...
def make_field_handle_empty(val) -> str: ...
def read_msg(buf: bytes) -> tuple: ...
def read_fields(buf: bytes) -> tuple: ...
