from _typeshed import Incomplete
from ibapi.const import DOUBLE_INFINITY as DOUBLE_INFINITY, INFINITY_STR as INFINITY_STR, UNSET_DOUBLE as UNSET_DOUBLE, UNSET_INTEGER as UNSET_INTEGER
from ibapi.errors import INVALID_SYMBOL as INVALID_SYMBOL
from ibapi.utils import ClientException as ClientException, isAsciiPrintable as isAsciiPrintable

logger: Incomplete

def make_msg_proto(msgId: int, protobufData: bytes) -> bytes: ...
def make_msg(msgId: int, useRawIntMsgId: bool, text: str) -> bytes: ...
def make_initial_msg(text: str) -> bytes: ...
def make_field(val) -> str: ...
def make_field_handle_empty(val) -> str: ...
def read_msg(buf: bytes) -> tuple: ...
def read_fields(buf: bytes) -> tuple: ...
